// src/pages/Admin/UserDetailReport.tsx
import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { 
  ArrowLeft, 
  Award, 
  PlayCircle, 
  Clock, 
  TrendingUp, 
  Save,
  MessageCircle,
  ChevronRight
} from 'lucide-react';
import { DUMMY_USERS } from '@/data/dummy/user.dummy';
import { DUMMY_SESSIONS } from '@/data/dummy/session.dummy';

export default function UserDetailReport() {
  const { userId } = useParams();
  const navigate = useNavigate();
  const [adminNotes, setAdminNotes] = useState('');
  
  const user = DUMMY_USERS.find(u => u.id === userId) || DUMMY_USERS[1];

  const handleSaveNotes = () => {
    alert('Notes saved for the user. They will see these in their "Next Steps" section.');
  };

  return (
    <div className="space-y-8 pb-12">
      <button 
        onClick={() => navigate('/admin/reports')}
        className="flex items-center gap-2 text-gwf-muted hover:text-gwf-primary font-bold transition-all"
      >
        <ArrowLeft size={18} className="pointer-events-none" /> Back to Reports
      </button>

      {/* User Header */}
      <div className="bg-white p-8 rounded-[32px] border border-gwf-border shadow-md flex flex-col md:flex-row items-center gap-8">
        <div className="w-24 h-24 rounded-full border-4 border-gwf-primary overflow-hidden shadow-lg">
          <img src={user.avatar} alt="" className="w-full h-full object-cover" />
        </div>
        <div className="flex-1 text-center md:text-left space-y-1">
           <h2 className="text-3xl font-black italic text-gwf-text">{user.fullName}</h2>
           <div className="flex flex-wrap justify-center md:justify-start gap-4 text-[10px] font-black uppercase tracking-widest text-gwf-muted italic">
              <span>{user.ageGroup}</span>
              <span>•</span>
              <span className="text-gwf-primary">Streak: {user.dailyStreakCount} Days</span>
              <span>•</span>
              <span className="text-gwf-accent">Avg Score: 82%</span>
           </div>
        </div>
        <div className="flex gap-4">
           <div className="bg-gwf-bg p-4 rounded-2xl text-center min-w-[100px]">
              <p className="text-2xl font-black italic text-gwf-text">{user.totalSessionsPlayed}</p>
              <p className="text-[9px] font-black uppercase text-gwf-muted">Sessions</p>
           </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Column: Mistake Breakdown & Improvement */}
        <div className="lg:col-span-2 space-y-8">
          {/* Session History */}
          <div className="space-y-4">
            <h3 className="text-lg font-black italic text-gwf-text uppercase tracking-tight">Recent Sessions</h3>
            <div className="bg-white rounded-2xl border border-gwf-border shadow-sm overflow-hidden">
               <table className="w-full text-left">
                 <thead className="bg-gwf-bg/50 border-b border-gwf-border">
                   <tr>
                     <th className="px-6 py-4 text-[10px] font-black uppercase text-gwf-muted">Date</th>
                     <th className="px-6 py-4 text-[10px] font-black uppercase text-gwf-muted">Script</th>
                     <th className="px-6 py-4 text-[10px] font-black uppercase text-gwf-muted">Score</th>
                     <th className="px-6 py-4 text-[10px] font-black uppercase text-gwf-muted text-right">Action</th>
                   </tr>
                 </thead>
                 <tbody className="divide-y divide-gwf-border">
                   {DUMMY_SESSIONS.slice(0, 5).map(session => (
                     <tr key={session.id} className="hover:bg-gwf-bg/20 transition-colors">
                       <td className="px-6 py-4 text-xs font-bold text-gwf-muted">
                         {new Date(session.createdDate?.seconds * 1000).toLocaleDateString()}
                       </td>
                       <td className="px-6 py-4 font-bold text-sm">{session.sessionName}</td>
                       <td className="px-6 py-4">
                         <span className="font-black text-gwf-primary">{(Math.random() * 20 + 70).toFixed(0)}%</span>
                       </td>
                       <td className="px-6 py-4 text-right">
                         <button 
                           onClick={() => navigate(`/session/report/${session.id}`)}
                           className="p-2 text-gwf-muted hover:text-gwf-primary hover:bg-gwf-primary/10 rounded-full transition-all"
                           title="View Session Report"
                         >
                           <ChevronRight size={16} className="pointer-events-none" />
                         </button>
                       </td>
                     </tr>
                   ))}
                 </tbody>
               </table>
            </div>
          </div>

          {/* Improvement Trend */}
          <div className="space-y-4">
            <h3 className="text-lg font-black italic text-gwf-text uppercase tracking-tight">Weekly Progress Trend</h3>
            <div className="bg-white p-6 rounded-2xl border border-gwf-border shadow-sm">
               <div className="flex items-stretch h-52 gap-4 pt-10">
                  {(user.weeklyProgress || [65, 72, 68, 82]).map((score, i) => (
                    <div key={i} className="flex-1 flex flex-col items-center gap-3">
                       <div className="w-full flex-1 bg-gwf-bg/50 rounded-t-2xl relative flex items-end">
                          <motion.div 
                            initial={{ height: 0 }}
                            animate={{ height: `${score}%` }}
                            className="w-full bg-gwf-accent rounded-t-lg relative"
                          >
                             <span className="absolute -top-7 left-1/2 -translate-x-1/2 text-[11px] font-black text-gwf-accent whitespace-nowrap bg-white/80 px-1 rounded-md">
                               {score}%
                             </span>
                          </motion.div>
                       </div>
                       <span className="text-[10px] font-black uppercase text-gwf-muted tracking-widest italic shrink-0">Week {i + 1}</span>
                    </div>
                  ))}
               </div>
            </div>
          </div>
        </div>

        {/* Right Column: Weak Areas & Admin Notes */}
        <div className="space-y-8">
           <div className="space-y-4">
              <h3 className="text-lg font-black italic text-gwf-text uppercase tracking-tight">Main Weak Areas</h3>
              <div className="bg-white p-6 rounded-2xl border border-gwf-border shadow-sm space-y-6">
                 <ProgressItem label="Have Been (Perfect Tense)" value={65} color="bg-gwf-primary" />
                 <ProgressItem label="Phoneme: /θ/ (Th-sound)" value={42} color="bg-gwf-accent" />
                 <ProgressItem label="Speaking Speed (Fluency)" value={28} color="bg-gwf-warning" />
                 <ProgressItem label="Omitted Articles (a, an, the)" value={15} color="bg-gwf-error" />
              </div>
           </div>

           <div className="space-y-4">
              <h3 className="text-lg font-black italic text-gwf-text uppercase tracking-tight">Admin Recommendations</h3>
              <div className="bg-gwf-primary p-6 rounded-3xl text-white space-y-4 shadow-xl">
                 <div className="flex items-center gap-2">
                    <MessageCircle size={20} className="italic" />
                    <span className="text-xs font-black uppercase tracking-[0.1em]">Mentor Notes</span>
                 </div>
                 <textarea 
                   rows={4}
                   value={adminNotes}
                   onChange={(e) => setAdminNotes(e.target.value)}
                   placeholder="Type focusing steps for this user..."
                   className="w-full bg-white/10 border border-white/20 rounded-xl p-4 text-sm font-medium placeholder:text-white/50 focus:bg-white/20 outline-none transition-all"
                 />
                 <button 
                   onClick={handleSaveNotes}
                   className="w-full py-3 bg-white text-gwf-primary rounded-xl font-black uppercase text-xs shadow-lg flex items-center justify-center gap-2 hover:bg-gwf-bg transition-colors"
                 >
                    <Save size={16} className="pointer-events-none" /> Update User Path
                 </button>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
}

function ProgressItem({ label, value, color }: { label: string, value: number, color: string }) {
  return (
    <div className="space-y-2">
      <div className="flex justify-between text-[10px] font-black uppercase italic tracking-tight">
        <span className="text-gwf-text">{label}</span>
        <span className="text-gwf-muted">{value}% Frequency</span>
      </div>
      <div className="h-1.5 bg-gwf-bg rounded-full overflow-hidden">
        <motion.div 
          initial={{ width: 0 }}
          animate={{ width: `${value}%` }}
          className={`h-full ${color}`}
        />
      </div>
    </div>
  );
}

// src/app/modules/admin/reports/user-detail-report.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AdminService } from '@core/services/admin.service';
import { LucideAngularModule, ChevronLeft, Calendar, Clock, BarChart3, AlertTriangle, TrendingUp, Save, FileText } from 'lucide-angular';
import { MatTableModule } from '@angular/material/table';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { ToastService } from '@core/services/toast.service';

@Component({
  selector: 'app-user-detail-report',
  standalone: true,
  imports: [CommonModule, RouterLink, LucideAngularModule, MatTableModule, ReactiveFormsModule],
  template: `
    <div class="space-y-8 animate-in fade-in duration-500 pb-12">
      <!-- Header -->
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div class="flex items-center gap-6">
          <a routerLink="/admin/reports" class="p-3 bg-white border border-gw-card-border rounded-2xl text-gw-text-muted hover:text-gw-primary hover:border-gw-primary transition-all shadow-sm group">
            <i-lucide [img]="BackIcon" size="20" class="group-hover:-translate-x-1 transition-transform"></i-lucide>
          </a>
          <div class="flex items-center gap-4">
            <div class="w-16 h-16 rounded-2xl bg-gw-bg border border-gw-card-border p-1">
              <img [src]="report()?.user?.avatar" class="w-full h-full object-cover rounded-xl">
            </div>
            <div>
              <h2 class="text-2xl font-black text-gw-text italic tracking-tight">{{ report()?.user?.name }}</h2>
              <div class="flex items-center gap-4 mt-1">
                <span class="flex items-center gap-1 text-[10px] font-black uppercase tracking-widest text-gw-text-muted">
                   <i-lucide [img]="FlameIcon" size="14" class="text-gw-primary"></i-lucide>
                   {{ report()?.user?.streak }} Day Streak
                </span>
                <span class="flex items-center gap-1 text-[10px] font-black uppercase tracking-widest text-gw-text-muted">
                   <i-lucide [img]="SessionIcon" size="14" class="text-gw-accent"></i-lucide>
                   {{ report()?.user?.sessions }} Sessions
                </span>
                <span class="text-[10px] font-black uppercase tracking-widest text-gw-success">
                   {{ report()?.user?.avgScore }}% Avg Score
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="grid lg:grid-cols-3 gap-8">
        <!-- Main Stats & History -->
        <div class="lg:col-span-2 space-y-8">
          <!-- Session History -->
          <div class="space-y-4">
            <h3 class="text-lg font-black text-gw-text italic uppercase tracking-tight px-2">Session History</h3>
            <div class="bg-white rounded-3xl border border-gw-card-border shadow-sm overflow-hidden">
              <table mat-table [dataSource]="report()?.sessionHistory || []" class="w-full">
                <ng-container matColumnDef="date">
                  <th mat-header-cell *matHeaderCellDef class="px-6 py-4 font-black uppercase text-[10px] tracking-widest text-gw-text-muted">Date</th>
                  <td mat-cell *matCellDef="let row" class="px-6 py-4 text-xs font-bold text-gw-text-muted">{{ row.date | date:'mediumDate' }}</td>
                </ng-container>

                <ng-container matColumnDef="script">
                  <th mat-header-cell *matHeaderCellDef class="py-4 font-black uppercase text-[10px] tracking-widest text-gw-text-muted">Script</th>
                  <td mat-cell *matCellDef="let row" class="py-4">
                    <span class="font-bold text-gw-text">{{ row.script }}</span>
                  </td>
                </ng-container>

                <ng-container matColumnDef="duration">
                  <th mat-header-cell *matHeaderCellDef class="py-4 font-black uppercase text-[10px] tracking-widest text-gw-text-muted">Duration</th>
                  <td mat-cell *matCellDef="let row" class="py-4 text-xs font-medium text-gw-text-muted">{{ row.duration }}</td>
                </ng-container>

                <ng-container matColumnDef="fluency">
                  <th mat-header-cell *matHeaderCellDef class="py-4 font-black uppercase text-[10px] tracking-widest text-gw-text-muted">Fluency</th>
                  <td mat-cell *matCellDef="let row" class="py-4 font-black text-gw-success">{{ row.fluency }}%</td>
                </ng-container>

                <ng-container matColumnDef="mistakes">
                  <th mat-header-cell *matHeaderCellDef class="py-4 pr-6 font-black uppercase text-[10px] tracking-widest text-gw-text-muted text-center">Mistakes</th>
                  <td mat-cell *matCellDef="let row" class="py-4 pr-6 text-center">
                    <span class="text-xs font-black text-gw-error tabular-nums">{{ row.mistakes }}</span>
                  </td>
                </ng-container>

                <tr mat-header-row *matHeaderRowDef="historyColumns"></tr>
                <tr mat-row *matRowDef="let row; columns: historyColumns;" class="hover:bg-gw-bg/50 transition-colors"></tr>
              </table>
            </div>
          </div>

          <!-- Improvement Trend -->
          <div class="space-y-4">
            <h3 class="text-lg font-black text-gw-text italic uppercase tracking-tight px-2">Improvement Trend</h3>
            <div class="bg-white rounded-3xl border border-gw-card-border shadow-sm p-6 overflow-hidden">
               <table class="w-full">
                  <thead>
                    <tr class="border-b border-gw-card-border">
                        <th class="py-4 text-left font-black uppercase text-[10px] tracking-widest text-gw-text-muted">Period</th>
                        <th class="py-4 text-right font-black uppercase text-[10px] tracking-widest text-gw-text-muted">Avg Fluency</th>
                        <th class="py-4 text-right font-black uppercase text-[10px] tracking-widest text-gw-text-muted">Growth</th>
                    </tr>
                  </thead>
                  <tbody>
                    @for (trend of report()?.improvementTrend; track trend.week; let i = index) {
                      <tr class="border-b border-gw-bg last:border-0 hover:bg-gw-bg/30 transition-colors">
                        <td class="py-4 text-sm font-bold text-gw-text">{{ trend.week }}</td>
                        <td class="py-4 text-right">
                           <span class="text-sm font-black text-gw-primary">{{ trend.fluency }}%</span>
                        </td>
                        <td class="py-4 text-right">
                           @if (i > 0) {
                             <div class="flex items-center justify-end gap-1 text-gw-success">
                                <i-lucide [img]="TrendIcon" size="12"></i-lucide>
                                <span class="text-xs font-black">+{{ trend.fluency - report()!.improvementTrend[i-1].fluency }}%</span>
                             </div>
                           } @else {
                             <span class="text-xs font-bold text-gw-text-muted italic">Baseline</span>
                           }
                        </td>
                      </tr>
                    }
                  </tbody>
               </table>
            </div>
          </div>
        </div>

        <!-- Sidebar Section -->
        <div class="space-y-8">
           <!-- Mistake Breakdown -->
           <div class="space-y-4">
              <h3 class="text-lg font-black text-gw-text italic uppercase tracking-tight px-2">Mistake Breakdown</h3>
              <div class="bg-white p-6 rounded-3xl border border-gw-card-border shadow-sm space-y-6">
                @for (item of report()?.mistakeBreakdown; track item.label) {
                  <div class="space-y-2">
                    <div class="flex justify-between items-end">
                      <span class="text-sm font-bold text-gw-text">{{ item.label }}</span>
                      <span class="text-[10px] font-black text-gw-text-muted uppercase tracking-widest italic">{{ item.count }} Errors</span>
                    </div>
                    <div class="h-2 bg-gw-bg rounded-full overflow-hidden">
                      <div 
                        class="h-full bg-gw-error rounded-full transition-all duration-1000 shadow-[0_0_8px_rgba(211,47,47,0.3)]"
                        [style.width.%]="item.percentage"
                      ></div>
                    </div>
                  </div>
                }
              </div>
           </div>

           <!-- Admin Notes -->
           <div class="space-y-4">
              <h3 class="text-lg font-black text-gw-text italic uppercase tracking-tight px-2">Admin Notes</h3>
              <div class="bg-white p-6 rounded-3xl border border-gw-card-border shadow-sm space-y-4">
                 <textarea 
                   [formControl]="notesControl"
                   class="w-full min-h-[160px] bg-gw-bg/50 border border-gw-card-border rounded-2xl p-4 text-sm font-medium text-gw-text focus:border-gw-primary outline-none transition-all resize-none placeholder:italic"
                   placeholder="Observation details, suggestions for user..."
                 ></textarea>
                 <button 
                   (click)="saveNotes()"
                   class="w-full h-12 bg-gw-text text-white font-black uppercase tracking-widest italic rounded-xl hover:scale-[1.02] active:scale-95 transition-all flex items-center justify-center gap-2"
                   [disabled]="isSaving()"
                 >
                   <i-lucide [img]="SaveIcon" size="18"></i-lucide>
                   {{ isSaving() ? 'Saving...' : 'Save Notes' }}
                 </button>
              </div>
           </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    :host { display: block; }
    .mat-mdc-table { background: transparent; }
    .mat-mdc-header-cell { border-bottom: 1px solid var(--gw-card-border); color: var(--gw-text-muted); }
  `]
})
export class UserDetailReportComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private adminService = inject(AdminService);
  private toast = inject(ToastService);

  readonly BackIcon = ChevronLeft;
  readonly FlameIcon = BarChart3; // Placeholder
  readonly SessionIcon = FileText;
  readonly TrendIcon = TrendingUp;
  readonly SaveIcon = Save;

  report = signal<any>(null);
  notesControl = new FormControl('');
  isSaving = signal(false);

  historyColumns = ['date', 'script', 'duration', 'fluency', 'mistakes'];

  ngOnInit() {
    this.route.params.subscribe(params => {
      const userId = params['id'];
      if (userId) {
        this.loadReport(userId);
      }
    });
  }

  loadReport(userId: string) {
    this.adminService.getUserFullReport(userId).subscribe(data => {
      this.report.set(data);
      this.notesControl.setValue(data.notes || '');
    });
  }

  saveNotes() {
    if (!this.report()) return;
    
    this.isSaving.set(true);
    this.adminService.addAdminNote({ 
      userId: this.report().user.id, 
      note: this.notesControl.value || '' 
    }).subscribe({
      next: () => {
        this.isSaving.set(false);
        this.toast.success('Admin notes updated');
      },
      error: () => this.isSaving.set(false)
    });
  }
}
