// src/app/modules/session/session-report/session-report.component.ts
// File: src/app/modules/session/session-report/session-report.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { LiveSessionService } from '../../live-session/live-session.service';
import { RepracticeService } from '../../repractice/repractice.service';
import { LucideAngularModule, CheckCircle2, Trophy, Clock, Target, Zap, ChevronRight, Home, Layout, History, MessageSquare, TrendingUp } from 'lucide-angular';
import { ToastService } from '@core/services/toast.service';

@Component({
  selector: 'app-session-report',
  standalone: true,
  imports: [CommonModule, LucideAngularModule, RouterLink],
  template: `
    <div class="space-y-12 animate-in zoom-in duration-700 pb-32">
      <!-- Success Header -->
      <div class="flex flex-col items-center gap-6 py-10 text-center">
         <div class="w-24 h-24 bg-gw-success/10 rounded-[40px] flex items-center justify-center text-gw-success shadow-xl shadow-gw-success/5 animate-bounce">
            <i-lucide [img]="SuccessIcon" size="48"></i-lucide>
         </div>
         <div class="space-y-2">
            <h2 class="text-4xl font-black text-gw-text italic uppercase tracking-tight">SESSION COMPLETE!</h2>
            <p class="text-sm font-bold text-gw-text-muted uppercase tracking-widest italic">Great progress today, flow forward!</p>
         </div>
      </div>

      <!-- Quick Summary Row -->
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
         <div class="bg-white p-6 rounded-[32px] border border-gw-card-border shadow-sm space-y-1">
            <span class="text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">Session Mode</span>
            <p class="text-lg font-black text-gw-text italic uppercase">{{ summary()?.mode || 'Grammar Drill' }}</p>
         </div>
         <div class="bg-white p-6 rounded-[32px] border border-gw-card-border shadow-sm space-y-1 text-center bg-[#E07B39]/5 border-[#E07B39]/20">
            <span class="text-[8px] font-black uppercase tracking-widest text-[#E07B39] italic">Top Score</span>
            <p class="text-2xl font-black text-[#E07B39] italic">{{ summary()?.topScore || 95 }}%</p>
         </div>
         <div class="bg-white p-6 rounded-[32px] border border-gw-card-border shadow-sm space-y-1">
            <span class="text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">Total Mistakes</span>
            <p class="text-2xl font-black text-gw-error italic">{{ summary()?.totalMistakes || 8 }}</p>
         </div>
         <div class="bg-white p-6 rounded-[32px] border border-gw-card-border shadow-sm space-y-1">
            <span class="text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">Duration</span>
            <p class="text-2xl font-black text-gw-text italic">12:45</p>
         </div>
      </div>

      <!-- Scoreboard -->
      <div class="space-y-6">
         <h3 class="text-lg font-black text-gw-text italic uppercase tracking-widest border-l-4 border-gw-primary pl-4">Leaderboard</h3>
         <div class="bg-white rounded-[40px] border border-gw-card-border overflow-hidden">
            <table class="w-full">
               <thead>
                  <tr class="bg-gw-bg/50">
                     <th class="px-8 py-4 text-left text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">Member</th>
                     <th class="px-8 py-4 text-center text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">Fluency</th>
                     <th class="px-8 py-4 text-center text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">Rating</th>
                     <th class="px-8 py-4 text-center text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">Mistakes</th>
                  </tr>
               </thead>
               <tbody class="divide-y divide-gw-bg">
                  @for (score of scoreboard; track score.name; let i = $index) {
                    <tr class="hover:bg-gw-bg/20 transition-colors" [class.bg-gw-primary/5]="i === 0">
                       <td class="px-8 py-6">
                          <div class="flex items-center gap-3">
                             @if (i === 0) { <i-lucide [img]="TrophyIcon" size="16" class="text-[#F59E0B]"></i-lucide> }
                             <img [src]="'https://api.dicebear.com/7.x/avataaars/svg?seed=' + score.name" class="w-8 h-8 rounded-lg">
                             <span class="font-bold italic text-gw-text text-sm">{{ score.name }}</span>
                          </div>
                       </td>
                       <td class="px-8 py-6 text-center">
                          <span class="text-sm font-black italic" [class.text-gw-success]="score.fluency >= 80">{{ score.fluency }}%</span>
                       </td>
                       <td class="px-8 py-6 text-center">
                          <span class="text-xs font-bold italic text-gw-primary">{{ score.rating }}</span>
                       </td>
                       <td class="px-8 py-6 text-center">
                          <span class="text-xs font-black italic" [class.text-gw-error]="score.mistakes > 0">{{ score.mistakes }}</span>
                       </td>
                    </tr>
                  }
               </tbody>
            </table>
         </div>
      </div>

      <!-- Improvement Note -->
      <div class="p-8 bg-[#1A1A2E] rounded-[48px] text-white flex flex-col md:flex-row items-center gap-8 relative overflow-hidden">
         <div class="absolute top-0 right-0 p-8 opacity-10">
            <i-lucide [img]="TrendingIcon" size="120"></i-lucide>
         </div>
         <div class="w-20 h-20 bg-gw-accent rounded-[32px] flex items-center justify-center text-white shadow-2xl shadow-gw-accent/40 rotate-3 shrink-0">
            <i-lucide [img]="TrendingIcon" size="32"></i-lucide>
         </div>
         <div class="space-y-2 relative z-10 text-center md:text-left">
            <h4 class="text-2xl font-black text-gw-accent italic uppercase tracking-tight">PROGRESS DETECTED!</h4>
            <p class="text-base font-bold text-white/80 italic leading-relaxed">
               "Your group improved 12% desde last session on this script! Fixed 3 common grammar mistakes together."
            </p>
         </div>
      </div>

      <!-- Actions -->
      <div class="space-y-4">
         <button (click)="startCorrection()" class="w-full h-20 bg-gw-primary text-white font-black uppercase tracking-widest italic rounded-3xl shadow-2xl shadow-gw-primary/20 hover:scale-[1.02] active:scale-95 transition-all flex flex-col items-center justify-center group">
            <div class="flex items-center gap-3">
               <i-lucide [img]="ZapIcon" size="24" class="text-gw-accent group-hover:animate-pulse"></i-lucide>
               <span class="text-xl">START CORRECTION ROUND</span>
            </div>
            <span class="text-[8px] opacity-60">PRACTICE YOUR 3 PERSONAL MISTAKES</span>
         </button>

         <div class="grid grid-cols-2 gap-4">
            <button [routerLink]="['/session', summary()?.id, 'detail']" class="h-16 bg-white border-2 border-gw-card-border text-gw-text font-black uppercase tracking-widest italic rounded-2xl flex items-center justify-center gap-2 hover:bg-gw-bg transition-all">
               <i-lucide [img]="LayoutIcon" size="18"></i-lucide>
               DETAILED REPORT
            </button>
            <button routerLink="/user/dashboard" class="h-16 bg-white border-2 border-gw-card-border text-gw-text font-black uppercase tracking-widest italic rounded-2xl flex items-center justify-center gap-2 hover:bg-gw-bg transition-all">
               <i-lucide [img]="HomeIcon" size="18"></i-lucide>
               GO HOME
            </button>
         </div>
      </div>
    </div>
  `,
  styles: [`
    :host { display: block; }
  `]
})
export class SessionReportComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private liveSessionService = inject(LiveSessionService);
  private repracticeService = inject(RepracticeService);
  private toast = inject(ToastService);

  readonly SuccessIcon = CheckCircle2;
  readonly TrophyIcon = Trophy;
  readonly ZapIcon = Zap;
  readonly LayoutIcon = Layout;
  readonly HomeIcon = Home;
  readonly TrendingIcon = TrendingUp;

  summary = signal<any>(null);
  scoreboard = [
    { name: 'Arjun Kumar', fluency: 95, rating: 'Excellent', mistakes: 0 },
    { name: 'Ravi Kumar', fluency: 88, rating: 'Great', mistakes: 1 },
    { name: 'Priya Kumar', fluency: 82, rating: 'Good', mistakes: 2 },
    { name: 'Sneha Kumar', fluency: 75, rating: 'Improving', mistakes: 3 }
  ];

  ngOnInit() {
    this.route.params.subscribe(params => {
      const id = params['sessionId'];
      if (id) {
        // Normally calling complete session to get results
        this.liveSessionService.completeSession(id).subscribe(res => {
          this.summary.set({ id, ...res });
        });
      }
    });
  }

  startCorrection() {
    this.repracticeService.generateRepracticeSession(this.summary()?.id || '0').subscribe(res => {
      this.router.navigate(['/repractice', res.id]);
    });
  }
}

// src/pages/Assessment/SessionReport.tsx
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'motion/react';
import { 
  CheckCircle2, 
  TrendingUp, 
  Calendar, 
  Clock, 
  Target, 
  Star, 
  Users, 
  ArrowRight,
  RotateCcw,
  Volume2,
  Trophy,
  Activity,
  History,
  LayoutDashboard,
  Download
} from 'lucide-react';
import { useAuth } from '@/lib/AuthContext';
import { db } from '@/lib/firebase';
import { doc, getDoc, collection, query, where, getDocs } from 'firebase/firestore';
import { Session, Assessment, Member } from '@/types';
import { DUMMY_SESSIONS } from '@/data/dummy/session.dummy';

export default function SessionReport() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { user, isDemo } = useAuth();
  const [session, setSession] = useState<Session | null>(null);
  const [assessments, setAssessments] = useState<Assessment[]>([]);
  const [members, setMembers] = useState<Member[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;

    const fetchReport = async () => {
      try {
        if (isDemo) {
          const sData = DUMMY_SESSIONS.find(s => s.id === id);
          if (sData) {
            setSession(sData);
          }
          setLoading(false);
          return;
        }

        const sSnap = await getDoc(doc(db, 'sessions', id));
        if (sSnap.exists()) {
          setSession({ id: sSnap.id, ...sSnap.data() } as Session);

          // Fetch members from subcollection
          const mSnap = await getDocs(collection(db, 'sessions', id, 'members'));
          setMembers(mSnap.docs.map(d => ({ id: d.id, ...d.data() } as Member)));

          // Fetch assessments for the session
          const aQuery = query(collection(db, 'assessments'), where('sessionId', '==', id));
          const aSnap = await getDocs(aQuery);
          setAssessments(aSnap.docs.map(d => ({ id: d.id, ...d.data() } as Assessment)));
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchReport();
  }, [id]);

  if (loading) return (
     <div className="min-h-screen bg-gwf-bg flex items-center justify-center">
        <div className="animate-spin h-10 w-10 border-t-2 border-gwf-primary rounded-full"></div>
     </div>
  );

  if (!session && !loading) {
     return (
        <div className="min-h-screen bg-gwf-bg flex flex-col items-center justify-center p-6 text-center">
           <Activity size={48} className="text-gwf-muted opacity-20 mb-4" />
           <h2 className="text-xl font-black italic">Report Not Found</h2>
           <button onClick={() => navigate(-1)} className="mt-4 text-gwf-primary font-bold">Go Back</button>
        </div>
     );
  }

  if (!session) return null;

  // Calculate stats for current user
  const myAssessments = assessments.filter(a => a.candidateMemberId === user?.id);
  const avgFluency = myAssessments.length > 0 
    ? Math.round(myAssessments.reduce((acc, a) => acc + (a.ratings?.fluency || 0), 0) / myAssessments.length) * 20
    : 75; // Default for demo if no assessments yet

  // Best performer logic (simulated for demo if needed)
  const memberScores = members.length > 0 ? members.map(m => {
    const memberAssessments = assessments.filter(a => a.candidateMemberId === m.userId);
    const score = memberAssessments.length > 0 
      ? Math.round(memberAssessments.reduce((acc, a) => acc + (a.ratings?.fluency || 0), 0) / memberAssessments.length) * 20
      : Math.round(70 + Math.random() * 20);
    return { ...m, avgScore: score };
  }) : [
     { id: '1', name: user?.fullName || 'You', userId: user?.id, avgScore: avgFluency, avatar: user?.avatar },
     { id: '2', name: 'Aarav', userId: 'u2', avgScore: 88, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aarav' },
     { id: '3', name: 'Ishani', userId: 'u3', avgScore: 92, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ishani' }
  ];

  const bestPerformer = [...memberScores].sort((a, b) => b.avgScore - a.avgScore)[0];

  return (
    <div className="min-h-screen bg-gwf-bg selection:bg-gwf-primary/20 pb-24">
      <main className="max-w-3xl mx-auto p-6 md:p-12 space-y-12">
        
        {/* Celebration Header */}
        <section className="text-center space-y-6 pt-8">
           <motion.div 
             initial={{ scale: 0.8, opacity: 0 }}
             animate={{ scale: 1, opacity: 1 }}
             className="w-24 h-24 bg-gwf-success/20 rounded-[40px] flex items-center justify-center text-gwf-success mx-auto shadow-[0_0_50px_rgba(34,197,94,0.15)]"
           >
              <Trophy size={48} />
           </motion.div>
           
           <div className="space-y-2">
              <h1 className="text-4xl font-black italic tracking-tight text-gwf-text">Session Complete! ✓</h1>
              <div className="flex items-center justify-center gap-2 text-gwf-muted font-bold text-[10px] uppercase tracking-widest italic">
                 <span>{session.sessionName}</span>
                 <span className="w-1 h-1 bg-gwf-border rounded-full" />
                 <span>12 Minutes Sync</span>
              </div>
           </div>

           <div className="flex justify-center print:hidden">
              <button 
                onClick={() => window.print()}
                className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-gwf-primary bg-gwf-primary/5 px-4 py-2 rounded-xl border border-gwf-primary/10 hover:bg-gwf-primary/10 transition-all"
              >
                <Download size={14} /> Export PDF Report
              </button>
           </div>
        </section>

        {/* Global Stats Grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
           <ReportStat label="Avg Fluency" value={`${avgFluency}%`} color="text-gwf-primary" icon={<TrendingUp size={14} />} />
           <ReportStat label="Turns Sync'd" value={myAssessments.length || 10} color="text-gwf-text" icon={<History size={14} />} />
           <ReportStat label="Mistakes" value={5} color="text-gwf-error" icon={<Activity size={14} />} />
           <ReportStat label="Group Growth" value="+12%" color="text-gwf-accent" icon={<Star size={14} />} />
        </div>

        {/* Members Leaderboard */}
        <section className="space-y-4">
           <div className="flex items-center justify-between px-2">
              <h2 className="text-sm font-black italic uppercase text-gwf-muted px-1">Sync Leaderboard</h2>
              <div className="flex items-center gap-2 text-[10px] font-bold text-gwf-muted italic">
                 <Users size={12} /> {memberScores.length} Members Participated
              </div>
           </div>

           <div className="bg-white rounded-[40px] border border-gwf-border overflow-hidden shadow-sm">
              <table className="w-full text-left border-collapse">
                 <thead className="bg-gwf-bg/50 border-b border-gwf-border">
                    <tr>
                       <th className="px-6 py-4 text-[9px] font-black uppercase tracking-widest text-gwf-muted">Member</th>
                       <th className="px-6 py-4 text-[9px] font-black uppercase tracking-widest text-gwf-muted">Fluency</th>
                       <th className="px-6 py-4 text-[9px) font-black uppercase tracking-widest text-gwf-muted text-right">Rating</th>
                    </tr>
                 </thead>
                 <tbody className="divide-y divide-gwf-border">
                    {memberScores.map((m) => (
                      <tr key={m.userId} className={`${m.userId === bestPerformer?.userId ? 'bg-gwf-secondary/5' : ''} transition-colors`}>
                         <td className="px-6 py-4">
                            <div className="flex items-center gap-3">
                               <div className="w-8 h-8 rounded-xl bg-white border border-gwf-border p-0.5 overflow-hidden shadow-sm">
                                  <img src={m.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${m.name}`} className="w-full h-full object-cover rounded-lg" alt={m.name} />
                               </div>
                               <div className="flex flex-col">
                                  <span className="text-xs font-black italic">{m.name} {m.userId === user?.id && <span className="text-[8px] font-medium text-gwf-primary opacity-60">(You)</span>}</span>
                                  {m.userId === bestPerformer?.userId && <span className="text-[8px] font-black uppercase text-gwf-secondary flex items-center gap-1"><Trophy size={8} /> MVP</span>}
                               </div>
                            </div>
                         </td>
                         <td className="px-6 py-4">
                            <span className={`text-sm font-black italic ${m.avgScore >= 80 ? 'text-gwf-success' : m.avgScore >= 60 ? 'text-gwf-warning' : 'text-gwf-error'}`}>
                               {m.avgScore}%
                            </span>
                         </td>
                         <td className="px-6 py-4 text-right">
                            <div className="flex items-center justify-end gap-0.5">
                               {Array.from({ length: 5 }).map((_, i) => (
                                 <Star key={i} size={10} className={i < Math.floor(m.avgScore / 20) ? 'fill-gwf-warning text-gwf-warning' : 'text-gwf-border'} />
                               ))}
                            </div>
                         </td>
                      </tr>
                    ))}
                 </tbody>
              </table>
           </div>
        </section>

        {/* Improvement Insight */}
        <section className="bg-gwf-primary/5 rounded-[40px] border border-gwf-primary/10 p-8 flex flex-col md:flex-row items-center gap-8 shadow-inner">
           <div className="w-16 h-16 bg-gwf-primary rounded-3xl flex items-center justify-center text-white shadow-xl shadow-gwf-primary/20">
              <TrendingUp size={32} />
           </div>
           <div className="flex-1 space-y-1 text-center md:text-left">
              <h3 className="text-lg font-black italic">Rhythm Synchronized!</h3>
              <p className="text-sm font-medium italic text-gwf-muted">Your group improved collective fluency by <span className="text-gwf-primary font-bold">12%</span> compared to previous sessions on this script.</p>
           </div>
        </section>

        {/* Action Buttons */}
        <div className="flex flex-col gap-4">
           <button 
             onClick={() => navigate('/repractice/new')}
             className="w-full h-16 btn-primary rounded-3xl glow-primary flex items-center justify-center gap-3 italic font-black text-xl shadow-2xl"
           >
              Refine Your Mistakes <RotateCcw size={22} />
           </button>
           
           <div className="grid grid-cols-2 gap-4">
              <button 
                onClick={() => navigate(`/user/sessions/${id}`)}
                className="h-14 bg-white border-2 border-gwf-border rounded-[28px] flex items-center justify-center gap-2 font-black italic text-sm hover:border-gwf-primary/30 transition-all shadow-sm"
              >
                 Detailed Report <ArrowRight size={18} />
              </button>
              <button 
                onClick={() => navigate('/')}
                className="h-14 bg-white border-2 border-gwf-border rounded-[28px] flex items-center justify-center gap-2 font-black italic text-sm hover:border-gwf-primary/30 transition-all shadow-sm"
              >
                 Back to Dashboard <LayoutDashboard size={18} />
              </button>
           </div>
        </div>

      </main>
    </div>
  );
}

function ReportStat({ label, value, color, icon }: { label: string, value: string | number, color: string, icon: React.ReactNode }) {
  return (
    <div className="card-base flex flex-col gap-2 py-6 text-center hover:scale-105 transition-transform cursor-default">
       <div className="flex justify-center text-gwf-muted opacity-40">{icon}</div>
       <p className={`text-2xl font-black italic tracking-tighter ${color}`}>{value}</p>
       <p className="text-[9px] font-black uppercase text-gwf-muted tracking-widest">{label}</p>
    </div>
  );
}
