// src/app/shared/components/loader/loader.component.ts
// File: src/app/shared/components/loader/loader.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LoaderService } from '@core/services/loader.service';

@Component({
  selector: 'app-loader',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (isLoading()) {
      <div class="fixed inset-0 z-[10000] bg-white/85 flex flex-col items-center justify-center gap-6 animate-in fade-in duration-200">
         <div class="w-12 h-12 border-[3px] border-gw-bg border-t-gw-primary rounded-full animate-spin"></div>
         <p class="text-[10px] font-black uppercase tracking-widest italic text-gw-primary animate-pulse">Syncing your flow...</p>
      </div>
    }
  `,
  styles: [`
    :host { display: block; }
  `]
})
export class LoaderComponent {
  isLoading = inject(LoaderService).isLoading;
}

// src/components/Shared/Loader.tsx
import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { useLoader } from '@/lib/loaderService';

export default function LoaderOverlay() {
  const { isLoading, message } = useLoader();

  return (
    <AnimatePresence>
      {isLoading && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[200] bg-gwf-bg/80 backdrop-blur-sm flex flex-col items-center justify-center p-6 text-center"
        >
          <div className="relative">
             <div className="w-16 h-16 rounded-full border-4 border-gwf-primary/20 border-t-gwf-primary animate-spin" />
             <div className="absolute inset-0 flex items-center justify-center">
                <div className="w-8 h-8 bg-gwf-primary/10 rounded-full animate-pulse" />
             </div>
          </div>
          {message && (
             <motion.p 
               initial={{ opacity: 0, y: 10 }}
               animate={{ opacity: 1, y: 0 }}
               className="mt-6 text-gwf-text font-black italic tracking-tight"
             >
               {message}
             </motion.p>
          )}
        </motion.div>
      )}
    </AnimatePresence>
  );
}
