// src/app/shared/components/toast/toast.component.ts
// File: src/app/shared/components/toast/toast.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ToastService, Toast } from '@core/services/toast.service';
import { LucideAngularModule, CheckCircle, XCircle, Info, AlertTriangle, X } from 'lucide-angular';

@Component({
  selector: 'app-toast',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  template: `
    <div class="fixed bottom-6 left-1/2 -translate-x-1/2 z-[9999] flex flex-col gap-2 items-center pointer-events-none w-full max-w-sm px-4">
      @for (toast of toasts(); track toast) {
        <div 
          class="w-full bg-white border-l-4 shadow-2xl rounded-xl p-4 flex items-center gap-3 animate-in slide-in-from-bottom-2 fade-in duration-200 pointer-events-auto"
          [class.border-gw-success]="toast.type === 'success'"
          [class.border-gw-error]="toast.type === 'error'"
          [class.border-gw-primary]="toast.type === 'info'"
          [class.border-gw-warning]="toast.type === 'warning'"
        >
          <div [ngSwitch]="toast.type" class="shrink-0 flex items-center justify-center">
             <i-lucide *ngSwitchCase="'success'" [img]="CheckIcon" size="18" class="text-gw-success"></i-lucide>
             <i-lucide *ngSwitchCase="'error'" [img]="ErrorIcon" size="18" class="text-gw-error"></i-lucide>
             <i-lucide *ngSwitchCase="'info'" [img]="InfoIcon" size="18" class="text-gw-primary"></i-lucide>
             <i-lucide *ngSwitchCase="'warning'" [img]="WarnIcon" size="18" class="text-gw-warning"></i-lucide>
          </div>
          
          <p class="text-[13px] font-bold text-gw-text italic flex-1 leading-tight">{{ toast.message }}</p>
          
          <button (click)="toastService.toasts.set(toasts().filter(t => t !== toast))" class="text-gw-text-muted hover:text-gw-text shrink-0">
             <i-lucide [img]="CloseIcon" size="16"></i-lucide>
          </button>
        </div>
      }
    </div>
  `,
  styles: [`
    :host { display: block; }
  `]
})
export class ToastComponent {
  toastService = inject(ToastService);
  toasts = this.toastService.toasts;

  readonly CheckIcon = CheckCircle;
  readonly ErrorIcon = XCircle;
  readonly InfoIcon = Info;
  readonly WarnIcon = AlertTriangle;
  readonly CloseIcon = X;
}

// src/components/Shared/Toast.tsx
import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { CheckCircle2, AlertCircle, Info, AlertTriangle } from 'lucide-react';
import { useToasts, toastService } from '@/lib/toastService';

export default function ToastContainer() {
  const toasts = useToasts();

  return (
    <div className="fixed bottom-24 left-1/2 -translate-x-1/2 z-[100] w-full max-w-xs space-y-2 pointer-events-none">
      <AnimatePresence>
        {toasts.map((toast) => (
          <motion.div
            key={toast.id}
            initial={{ opacity: 0, y: 20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            className={`pointer-events-auto glass p-4 rounded-2xl flex items-center gap-3 shadow-xl border-l-[6px] ${
              toast.type === 'success' ? 'border-l-gwf-success' :
              toast.type === 'error' ? 'border-l-gwf-error' :
              toast.type === 'warning' ? 'border-l-gwf-warning' :
              'border-l-gwf-primary'
            }`}
          >
            <div className={`p-1.5 rounded-lg ${
              toast.type === 'success' ? 'bg-gwf-success/10 text-gwf-success' :
              toast.type === 'error' ? 'bg-gwf-error/10 text-gwf-error' :
              toast.type === 'warning' ? 'bg-gwf-warning/10 text-gwf-warning' :
              'bg-gwf-primary/10 text-gwf-primary'
            }`}>
              {toast.type === 'success' && <CheckCircle2 size={18} />}
              {toast.type === 'error' && <AlertCircle size={18} />}
              {toast.type === 'warning' && <AlertTriangle size={18} />}
              {toast.type === 'info' && <Info size={18} />}
            </div>
            <p className="text-sm font-bold text-gwf-text italic">{toast.message}</p>
          </motion.div>
        ))}
      </AnimatePresence>
    </div>
  );
}
