// src/pages/Scripts/ScriptLibrary.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  BookOpen, 
  Search, 
  Filter, 
  Play, 
  Clock, 
  Users,
  ChevronRight,
  TrendingUp,
  Tag
} from 'lucide-react';
import { collection, getDocs, query, orderBy } from 'firebase/firestore';
import { db, auth } from '@/lib/firebase';
import { useAuth } from '@/lib/AuthContext';
import { Script } from '@/types';
import { DUMMY_SCRIPTS } from '@/data/dummy/script.dummy';

export default function ScriptLibrary() {
  const navigate = useNavigate();
  const { isDemo, user } = useAuth();
  const [scripts, setScripts] = useState<Script[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState<string>('All');

  useEffect(() => {
    const fetchScripts = async () => {
      try {
        if (isDemo) {
          setScripts(DUMMY_SCRIPTS);
          setLoading(false);
          return;
        }
        const snap = await getDocs(query(collection(db, 'scripts'), orderBy('uploadedDate', 'desc')));
        setScripts(snap.docs.map(d => ({ id: d.id, ...d.data() } as Script)));
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchScripts();
  }, []);

  const [selectedScriptForPreview, setSelectedScriptForPreview] = useState<Script | null>(null);

  const categories = ['All', 'Grammar Drill', 'Interview', 'Roleplay', 'Business', 'Travel'];
  const filtered = scripts.filter(s => 
    (category === 'All' || s.category === category) &&
    (s.title.toLowerCase().includes(search.toLowerCase()) || s.description.toLowerCase().includes(search.toLowerCase()))
  );

  return (
    <div className="space-y-8 p-6 pb-32">
       <div className="space-y-4">
          <div className="relative">
             <Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-gwf-muted pointer-events-none" />
             <input 
                type="text" 
                placeholder="Search synchronizable scripts..."
                className="gwf-input pl-12"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
             />
          </div>

          <div className="flex gap-2 overflow-x-auto pb-2 scrollbar-none">
             {categories.map(cat => (
                <button
                  key={cat}
                  onClick={() => setCategory(cat)}
                  className={`px-6 py-2 rounded-full text-xs font-black uppercase tracking-widest transition-all whitespace-nowrap border ${
                    category === cat ? 'bg-gwf-primary text-white border-gwf-primary' : 'bg-white text-gwf-muted border-gwf-border'
                  }`}
                >
                  {cat}
                </button>
             ))}
          </div>
       </div>

       {loading ? (
         <div className="flex items-center justify-center py-20">
            <div className="animate-spin h-8 w-8 border-t-2 border-gwf-primary rounded-full" />
         </div>
       ) : (
         <div className="grid gap-4">
            {filtered.map((script) => (
              <button 
                key={script.id}
                onClick={() => setSelectedScriptForPreview(script)}
                className="card-base text-left group hover:border-gwf-primary transition-all flex items-center justify-between gap-4"
              >
                 <div className="flex items-center gap-4">
                    <div className="w-16 h-16 bg-gwf-primary/5 rounded-2xl flex items-center justify-center text-gwf-primary group-hover:bg-gwf-primary group-hover:text-white transition-all">
                       <BookOpen size={24} className="pointer-events-none" />
                    </div>
                    <div className="space-y-1">
                       <div className="flex items-center gap-2">
                          <span className="px-2 py-0.5 bg-gwf-bg rounded text-[8px] font-black uppercase text-gwf-muted">{script.category}</span>
                          <span className="flex items-center gap-1 text-[8px] font-bold text-gwf-muted uppercase tracking-wider">
                             <Clock size={10} className="pointer-events-none" /> {script.estDuration}m
                          </span>
                       </div>
                       <h3 className="font-black italic text-gwf-text group-hover:text-gwf-primary transition-colors">{script.title}</h3>
                       <p className="text-[10px] text-gwf-muted line-clamp-1">{script.description}</p>
                    </div>
                 </div>
                 <div className="flex flex-col items-end gap-2">
                    <div className="flex -space-x-2">
                       {[1,2,3].map(i => (
                         <div key={i} className="w-5 h-5 rounded-full border-2 border-white bg-gwf-bg overflow-hidden">
                            <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${script.id}${i}`} />
                         </div>
                       ))}
                    </div>
                    <span className="text-[8px] font-black italic text-gwf-primary uppercase tracking-widest flex items-center gap-1">
                       Preview <ChevronRight size={10} className="pointer-events-none" />
                    </span>
                 </div>
              </button>
            ))}
            {filtered.length === 0 && (
              <div className="text-center py-20 opacity-40">
                 <Search size={48} className="mx-auto mb-4" />
                 <p className="font-black italic">No scripts found</p>
              </div>
            )}
         </div>
       )}

       {/* Script Detail Preview Modal */}
       {selectedScriptForPreview && (
          <div className="fixed inset-0 z-50 flex items-end justify-center p-4 bg-gwf-text/40 backdrop-blur-sm">
             <div className="w-full max-w-lg bg-gwf-bg rounded-[40px] shadow-2xl overflow-hidden animate-in slide-in-from-bottom duration-300">
                <div className="p-8 space-y-6">
                   <div className="flex items-start justify-between">
                      <div className="space-y-1">
                         <div className="flex items-center gap-2">
                            <span className="px-3 py-1 bg-gwf-primary/10 text-gwf-primary rounded-full text-[10px] font-black uppercase tracking-widest">{selectedScriptForPreview.category}</span>
                            <span className="text-[10px] font-bold text-gwf-muted uppercase tracking-widest flex items-center gap-1">
                               <TrendingUp size={12} /> Level {selectedScriptForPreview.complexityLevel}
                            </span>
                         </div>
                         <h2 className="text-3xl font-black italic text-gwf-text leading-tight">{selectedScriptForPreview.title}</h2>
                         <p className="text-sm text-gwf-muted font-medium">{selectedScriptForPreview.description}</p>
                      </div>
                      <button 
                        onClick={() => setSelectedScriptForPreview(null)}
                        className="p-2 bg-gwf-bg border border-gwf-border rounded-full hover:bg-white transition-colors"
                      >
                         <ChevronRight size={20} className="rotate-90" />
                      </button>
                   </div>

                   <div className="grid grid-cols-2 gap-4">
                      <div className="p-4 bg-white rounded-3xl border border-gwf-border flex items-center gap-4">
                         <div className="w-10 h-10 bg-gwf-primary/5 rounded-xl flex items-center justify-center text-gwf-primary">
                            <Clock size={20} />
                         </div>
                         <div>
                            <p className="text-[9px] font-black text-gwf-muted uppercase tracking-widest leading-none mb-1">Duration</p>
                            <p className="text-sm font-black italic">{selectedScriptForPreview.estDuration} Minutes</p>
                         </div>
                      </div>
                      <div className="p-4 bg-white rounded-3xl border border-gwf-border flex items-center gap-4">
                         <div className="w-10 h-10 bg-gwf-primary/5 rounded-xl flex items-center justify-center text-gwf-primary">
                            <Users size={20} />
                         </div>
                         <div>
                            <p className="text-[9px] font-black text-gwf-muted uppercase tracking-widest leading-none mb-1">Capacity</p>
                            <p className="text-sm font-black italic">Up to 5 Users</p>
                         </div>
                      </div>
                   </div>

                   <div className="space-y-3">
                      <p className="text-[10px] font-black uppercase text-gwf-muted tracking-[0.2em] ml-2">Utterance Samples</p>
                      <div className="space-y-2 bg-white/50 p-2 rounded-[32px] border border-gwf-border/50">
                         {selectedScriptForPreview.utterances.slice(0, 3).map((u, i) => (
                           <div key={i} className="p-4 bg-white rounded-2xl border border-gwf-border flex gap-4 items-start shadow-sm">
                              <span className="shrink-0 w-8 h-8 rounded-full bg-gwf-bg flex items-center justify-center text-[10px] font-black italic text-gwf-muted">P{i+1}</span>
                              <div className="space-y-1">
                                 <p className="text-[10px] font-black text-gwf-primary uppercase tracking-tighter">{u.speakerLabel}</p>
                                 <p className="text-xs font-bold leading-relaxed">{u.englishText}</p>
                                 {u.hintText && <p className="text-[10px] text-gwf-muted italic">{u.hintText}</p>}
                              </div>
                           </div>
                         ))}
                         <div className="py-2 text-center">
                            <p className="text-[10px] font-bold text-gwf-muted uppercase tracking-widest">+ {selectedScriptForPreview.utterances.length - 3} more utterances</p>
                         </div>
                      </div>
                   </div>

                    <div className="flex gap-3 pt-2">
                      <button 
                        onClick={() => setSelectedScriptForPreview(null)}
                        className="flex-1 px-8 py-5 bg-white border border-gwf-border rounded-2xl text-[11px] font-black uppercase tracking-[0.2em] hover:bg-gwf-bg transition-all text-center"
                      >
                         Close
                      </button>
                      {auth.currentUser && user?.role === 'ADMIN' && (
                        <button 
                          onClick={() => {
                            if (selectedScriptForPreview) {
                              navigate('/admin/sessions/create', { state: { scriptId: selectedScriptForPreview.id } });
                            }
                          }}
                          className="flex-[2] px-8 py-5 bg-gwf-primary text-white rounded-2xl text-[11px] font-black uppercase tracking-[0.2em] shadow-lg shadow-gwf-primary/20 flex items-center justify-center gap-2 hover:scale-[1.02] active:scale-95 transition-all"
                        >
                           Initialize Session <Play size={14} className="fill-white" />
                        </button>
                      )}
                   </div>
                </div>
             </div>
          </div>
       )}
    </div>
  );
}

// src/app/modules/scripts/script-library/script-library.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule, Search, Filter, BookOpen, Play, ChevronRight, Tags } from 'lucide-angular';
import { ScriptService, Script } from '@core/services/script.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-script-library',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  template: `
    <div class="p-6 space-y-8 animate-in fade-in duration-500">
      <div class="space-y-1">
        <h1 class="text-3xl font-black italic tracking-tighter uppercase text-ls-text">Script Library</h1>
        <p class="text-ls-text-muted font-medium">Choose a scenario to practice your fluency.</p>
      </div>

      <!-- Search & Filters -->
      <div class="flex flex-col md:flex-row gap-4">
        <div class="relative flex-1">
          <i-lucide [img]="SearchIcon" size="20" class="absolute left-4 top-1/2 -translate-y-1/2 text-ls-text-muted"></i-lucide>
          <input 
            type="text" 
            [(ngModel)]="filters.SearchTerm"
            (ngModelChange)="loadScripts()"
            placeholder="Search scenarios..."
            class="input-field pl-12"
          >
        </div>
        <div class="flex gap-2">
          <select 
            [(ngModel)]="filters.Category"
            (ngModelChange)="loadScripts()"
            class="h-14 bg-white border border-ls-card-border rounded-2xl px-4 font-bold text-xs uppercase tracking-widest outline-none focus:border-ls-primary transition-all cursor-pointer"
          >
            <option value="">All Categories</option>
            <option value="Grammar Drill">Grammar Drill</option>
            <option value="Roleplay">Roleplay</option>
            <option value="Mock Interview">Mock Interview</option>
          </select>
        </div>
      </div>

      <!-- Script Grid -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div *ngFor="let script of scripts" class="card group hover:border-ls-primary transition-all cursor-pointer">
           <div class="flex flex-col h-full gap-6">
              <div class="flex items-start justify-between">
                 <div class="w-12 h-12 bg-ls-bg rounded-2xl flex items-center justify-center text-ls-primary group-hover:bg-ls-primary group-hover:text-white transition-all">
                    <i-lucide [img]="BookIcon" size="24"></i-lucide>
                 </div>
                 <span class="text-[10px] font-black uppercase tracking-widest text-ls-text-muted px-2 py-1 bg-ls-bg rounded-lg">
                    v{{ script.version }}
                 </span>
              </div>

              <div class="space-y-1 flex-1">
                 <h3 class="text-lg font-black italic text-ls-text group-hover:text-ls-primary transition-all">{{ script.title }}</h3>
                 <p class="text-xs text-ls-text-muted font-medium line-clamp-2">{{ script.description || 'Practice conversational English in this realistic scenario.' }}</p>
              </div>

              <div class="flex flex-wrap gap-2">
                 <div class="flex items-center gap-1.5 px-2 py-1 bg-ls-bg rounded-lg text-[10px] font-black uppercase tracking-widest text-ls-text">
                    <i-lucide [img]="TagsIcon" size="12" class="text-ls-accent"></i-lucide>
                    {{ script.grammarFocusTag }}
                 </div>
                 <div class="px-2 py-1 bg-ls-bg rounded-lg text-[10px] font-black uppercase tracking-widest text-ls-text">
                    {{ script.targetAgeGroup }}
                 </div>
              </div>

              <button class="w-full btn-primary h-12 gap-2 text-xs">
                 <i-lucide [img]="PlayIcon" size="14"></i-lucide>
                 Start Session
              </button>
           </div>
        </div>
      </div>

      <!-- Loading State -->
      <div *ngIf="loading" class="flex justify-center py-20">
         <div class="w-8 h-8 border-4 border-ls-primary border-t-transparent rounded-full animate-spin"></div>
      </div>

      <!-- Empty State -->
      <div *ngIf="!loading && scripts.length === 0" class="text-center py-20 card border-dashed">
         <p class="text-ls-text-muted font-black italic uppercase tracking-widest">No scripts found matches your filter</p>
      </div>
    </div>
  `,
  styles: []
})
export class ScriptLibraryComponent implements OnInit {
  readonly SearchIcon = Search;
  readonly FilterIcon = Filter;
  readonly BookIcon = BookOpen;
  readonly PlayIcon = Play;
  readonly TagsIcon = Tags;

  scripts: Script[] = [];
  loading = false;
  filters = {
    SearchTerm: '',
    Category: '',
    PageNumber: 1,
    PageSize: 12
  };

  constructor(private scriptService: ScriptService) {}

  ngOnInit() {
    this.loadScripts();
  }

  loadScripts() {
    this.loading = true;
    this.scriptService.getScripts(this.filters).subscribe({
      next: (res) => {
        this.scripts = res.items;
        this.loading = false;
      },
      error: () => this.loading = false
    });
  }
}
