// src/app/modules/admin/admin-layout/admin-layout.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink, RouterLinkActive, RouterOutlet, ActivatedRoute, NavigationEnd } from '@angular/router';
import { LucideAngularModule, LayoutDashboard, Users, FileText, BarChart3, LogOut, Menu, X } from 'lucide-angular';
import { AuthService } from '@modules/auth/auth.service';
import { filter, map } from 'rxjs';

@Component({
  selector: 'app-admin-layout',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, RouterOutlet, LucideAngularModule],
  template: `
    <div class="flex h-screen bg-gw-bg overflow-hidden font-sans">
      <!-- Sidebar Desktop -->
      <aside 
        class="hidden lg:flex flex-col w-[240px] bg-white border-r border-gw-card-border shrink-0 z-30"
      >
        <div class="h-16 flex items-center px-6 border-b border-gw-card-border">
          <span class="text-xl font-black text-gw-primary italic tracking-tight">GoWithFlow</span>
        </div>

        <nav class="flex-1 py-6">
          <ul class="space-y-1">
            <li *ngFor="let item of menuItems">
              <a 
                [routerLink]="item.path" 
                routerLinkActive="active-link"
                class="flex items-center gap-3 px-6 py-3 text-gw-text-muted hover:text-gw-primary hover:bg-gw-primary/5 transition-all group border-l-[3px] border-transparent"
              >
                <i-lucide [img]="item.icon" size="20" class="group-hover:scale-110 transition-transform"></i-lucide>
                <span class="text-sm font-bold tracking-tight">{{ item.label }}</span>
              </a>
            </li>
          </ul>
        </nav>

        <div class="p-4 border-t border-gw-card-border">
          <button 
            (click)="logout()"
            class="flex items-center gap-3 w-full px-4 py-3 text-gw-text-muted hover:text-gw-error hover:bg-gw-error/5 rounded-xl transition-all group"
          >
            <i-lucide [img]="LogoutIcon" size="20"></i-lucide>
            <span class="text-sm font-bold">Logout</span>
          </button>
        </div>
      </aside>

      <!-- Mobile Sidebar Overlay -->
      <div 
        *ngIf="isMobileMenuOpen()" 
        class="fixed inset-0 bg-black/50 z-40 lg:hidden backdrop-blur-sm"
        (click)="closeMobileMenu()"
      ></div>

      <!-- Mobile Sidebar -->
      <aside 
        class="fixed inset-y-0 left-0 w-[240px] bg-white z-50 lg:hidden transform transition-transform duration-300 shadow-2xl"
        [class.translate-x-0]="isMobileMenuOpen()"
        [class.-translate-x-full]="!isMobileMenuOpen()"
      >
        <div class="h-16 flex items-center justify-between px-6 border-b border-gw-card-border">
          <span class="text-xl font-black text-gw-primary italic tracking-tight">GoWithFlow</span>
          <button (click)="closeMobileMenu()" class="text-gw-text-muted">
            <i-lucide [img]="CloseIcon" size="24"></i-lucide>
          </button>
        </div>
        <nav class="py-6">
          <ul class="space-y-1">
            <li *ngFor="let item of menuItems">
              <a 
                [routerLink]="item.path" 
                routerLinkActive="active-link"
                (click)="closeMobileMenu()"
                class="flex items-center gap-3 px-6 py-3 text-gw-text-muted hover:text-gw-primary hover:bg-gw-primary/5 transition-all group border-l-[3px] border-transparent"
              >
                <i-lucide [img]="item.icon" size="20"></i-lucide>
                <span class="text-sm font-bold">{{ item.label }}</span>
              </a>
            </li>
          </ul>
        </nav>
      </aside>

      <!-- Main Content -->
      <div class="flex-1 flex flex-col min-w-0">
        <!-- Top Bar -->
        <header class="h-16 bg-white border-b border-gw-card-border flex items-center justify-between px-4 lg:px-8 z-20 sticky top-0">
          <div class="flex items-center gap-4">
            <button 
              (click)="isMobileMenuOpen.set(true)" 
              class="lg:hidden p-2 text-gw-text-muted hover:bg-gw-bg rounded-lg"
            >
              <i-lucide [img]="MenuIcon" size="24"></i-lucide>
            </button>
            <h1 class="text-lg font-black text-gw-text uppercase italic tracking-tighter">{{ pageTitle() }}</h1>
          </div>

          <div class="flex items-center gap-4">
            <div class="hidden sm:flex flex-col items-end">
              <span class="text-xs font-black uppercase text-gw-text tracking-widest">{{ adminName }}</span>
              <span class="text-[10px] font-bold text-gw-text-muted uppercase">Administrator</span>
            </div>
            <div class="w-10 h-10 rounded-xl bg-gw-bg border border-gw-card-border overflow-hidden flex items-center justify-center">
               <img [src]="adminAvatar" class="w-full h-full object-cover">
            </div>
            <button (click)="logout()" class="p-2 text-gw-text-muted hover:text-gw-error transition-colors">
              <i-lucide [img]="LogoutIcon" size="20"></i-lucide>
            </button>
          </div>
        </header>

        <!-- Page Area -->
        <main class="flex-1 overflow-y-auto p-4 lg:p-8">
          <router-outlet></router-outlet>
        </main>
      </div>
    </div>
  `,
  styles: [`
    .active-link {
      @apply bg-gw-primary/5 text-gw-primary border-gw-primary;
    }
  `]
})
export class AdminLayoutComponent {
  private auth = inject(AuthService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  isMobileMenuOpen = signal(false);
  pageTitle = signal('Dashboard');

  adminName = 'GoWithFlow Admin';
  adminAvatar = 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin';

  readonly menuItems = [
    { label: 'Dashboard', path: '/admin/dashboard', icon: LayoutDashboard },
    { label: 'Users', path: '/admin/users', icon: Users },
    { label: 'Scripts', path: '/admin/scripts', icon: FileText },
    { label: 'Reports', path: '/admin/reports', icon: BarChart3 },
  ];

  readonly LogoutIcon = LogOut;
  readonly MenuIcon = Menu;
  readonly CloseIcon = X;

  constructor() {
    this.router.events.pipe(
      filter(event => event instanceof NavigationEnd),
      map(() => {
        let currentRoute = this.route.root;
        while (currentRoute.firstChild) {
          currentRoute = currentRoute.firstChild;
        }
        return currentRoute.snapshot.data['title'] || 'Admin';
      })
    ).subscribe(title => this.pageTitle.set(title));
  }

  closeMobileMenu() {
    this.isMobileMenuOpen.set(false);
  }

  logout() {
    this.auth.logout();
  }
}

<div class="admin-shell">
  <div class="sidebar-overlay" [class.visible]="sidebarOpen" (click)="closeSidebar()"></div>

  <aside class="admin-sidebar" [class.open]="sidebarOpen">
    <div class="sidebar-logo">
      <div class="sidebar-logo-icon">G</div>
      <div>
        <div style="font-weight: 700; color: white; font-size: 18px; line-height: 1;">GoWithFlow</div>
        <div style="font-size: 10px; color: rgba(255,255,255,0.5); letter-spacing: 1px; margin-top: 2px;">ADMIN CONSOLE</div>
      </div>
    </div>

    <div class="sidebar-section-label">Main Menu</div>
    
    <nav class="sidebar-nav">
      <a routerLink="/admin/dashboard" routerLinkActive="active" class="nav-item" (click)="closeSidebar()">
        <mat-icon>dashboard</mat-icon>
        <span>Dashboard</span>
      </a>
      <a routerLink="/admin/users" routerLinkActive="active" class="nav-item" (click)="closeSidebar()">
        <mat-icon>people</mat-icon>
        <span>Users</span>
      </a>
      <a routerLink="/admin/scripts" routerLinkActive="active" class="nav-item" (click)="closeSidebar()">
        <mat-icon>description</mat-icon>
        <span>Scripts</span>
      </a>
      <a routerLink="/admin/reports" routerLinkActive="active" class="nav-item" (click)="closeSidebar()">
        <mat-icon>bar_chart</mat-icon>
        <span>Reports</span>
      </a>
    </nav>

    <div class="sidebar-footer">
      <div class="sidebar-user">
        <img [src]="adminAvatar" alt="Admin" class="sidebar-user-avatar" onerror="this.src='https://ui-avatars.com/api/?name=Admin&background=3D5A99&color=fff'">
        <div style="flex: 1; min-width: 0;">
          <div class="sidebar-user-name">{{ adminName }}</div>
          <div class="sidebar-user-role">Administrator</div>
        </div>
        <button mat-icon-button (click)="logout()" style="color: #7A8CA8;">
          <mat-icon>logout</mat-icon>
        </button>
      </div>
    </div>
  </aside>

  <div class="admin-main">
    <header class="admin-topbar">
      <div style="display: flex; align-items: center; gap: 16px;">
        <button mat-icon-button class="hamburger-btn" (click)="toggleSidebar()">
          <mat-icon>menu</mat-icon>
        </button>
        <div>
          <div class="topbar-breadcrumb-sub">Administration</div>
          <h1 class="topbar-breadcrumb-title">{{ pageTitle() }}</h1>
        </div>
      </div>

      <div style="display: flex; align-items: center; gap: 16px;">
        <div class="topbar-admin-info" style="text-align: right;">
          <div class="topbar-admin-name">{{ adminName }}</div>
          <div class="topbar-admin-role">Administrator</div>
        </div>
        <img [src]="adminAvatar" alt="Admin" class="topbar-avatar" onerror="this.src='https://ui-avatars.com/api/?name=Admin&background=3D5A99&color=fff'">
      </div>
    </header>

    <main class="admin-content">
      <router-outlet></router-outlet>
    </main>
  </div>
</div>

// src/components/Admin/AdminLayout.tsx
import React from 'react';
import { Link, useNavigate, useLocation, Outlet } from 'react-router-dom';
import { 
  LayoutDashboard, 
  Users, 
  FileText, 
  PlayCircle, 
  TrendingUp, 
  Settings, 
  LogOut,
  Menu,
  X,
  Wind
} from 'lucide-react';
import { useAuth } from '@/lib/AuthContext';
import { motion, AnimatePresence } from 'motion/react';

export default function AdminLayout() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [isMobileMenuOpen, setIsMobileMenuOpen] = React.useState(false);

  const navLinks = [
    { name: 'Dashboard', path: '/admin/dashboard', icon: LayoutDashboard },
    { name: 'Users', path: '/admin/users', icon: Users },
    { name: 'Scripts', path: '/admin/scripts', icon: FileText },
    { name: 'Sessions', path: '/admin/sessions', icon: PlayCircle },
    { name: 'Reports', path: '/admin/reports', icon: TrendingUp },
    { name: 'Settings', path: '/admin/settings', icon: Settings },
  ];

  const handleLogout = async () => {
    await logout();
    navigate('/login');
  };

  const PageTitle = navLinks.find(link => location.pathname.startsWith(link.path))?.name || 'Dashboard';

  return (
    <div className="min-h-screen bg-gwf-bg flex">
      {/* Sidebar - Desktop */}
      <aside className="w-64 bg-white border-r border-gwf-border hidden md:flex flex-col sticky top-0 h-screen">
        <div className="p-8">
          <h1 
            onClick={() => navigate('/admin/dashboard')}
            className="text-2xl font-black italic tracking-tighter text-gwf-primary flex items-center gap-2 cursor-pointer hover:opacity-80 transition-opacity"
          >
            <Wind className="text-gwf-accent" size={28} />
            <span>Go With Flow<span className="text-gwf-accent">.</span></span>
          </h1>
          <p className="text-[10px] font-black uppercase text-gwf-muted tracking-widest mt-1">Admin Portal</p>
        </div>

        <nav className="flex-1 px-4 space-y-2">
          {navLinks.map((link) => {
            const Icon = link.icon;
            const isActive = location.pathname.startsWith(link.path);
            return (
              <Link
                key={link.path}
                to={link.path}
                className={`flex items-center gap-3 px-4 py-3 rounded-xl font-bold transition-all ${
                  isActive 
                    ? 'bg-gwf-primary/10 text-gwf-primary border-l-4 border-gwf-primary' 
                    : 'text-gwf-muted hover:text-gwf-primary hover:bg-gwf-primary/5'
                }`}
              >
                <Icon size={20} /> {link.name}
              </Link>
            );
          })}
        </nav>

        <div className="p-4 border-t border-gwf-border">
          <button 
            onClick={handleLogout}
            className="w-full flex items-center gap-3 px-4 py-3 text-gwf-error hover:bg-gwf-error/5 rounded-xl font-bold transition-all text-sm uppercase tracking-wider"
          >
            <LogOut size={20} /> Logout
          </button>
        </div>
      </aside>

      {/* Mobile Sidebar */}
      <AnimatePresence>
        {isMobileMenuOpen && (
          <>
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsMobileMenuOpen(false)}
              className="fixed inset-0 bg-black/50 z-40 md:hidden"
            />
            <motion.aside 
              initial={{ x: '-100%' }}
              animate={{ x: 0 }}
              exit={{ x: '-100%' }}
              className="fixed inset-y-0 left-0 w-72 bg-white z-50 md:hidden p-4 flex flex-col shadow-2xl"
            >
              <div className="flex items-center justify-between mb-8 p-4">
                <h1 
                  onClick={() => {
                    navigate('/admin/dashboard');
                    setIsMobileMenuOpen(false);
                  }}
                  className="text-2xl font-black italic tracking-tighter text-gwf-primary flex items-center gap-2 cursor-pointer hover:opacity-80 transition-opacity"
                >
                  <Wind className="text-gwf-accent" size={28} />
                  <span>Go With Flow<span className="text-gwf-accent">.</span></span>
                </h1>
                <button onClick={() => setIsMobileMenuOpen(false)} className="p-2 text-gwf-muted">
                  <X size={24} />
                </button>
              </div>

              <nav className="flex-1 space-y-2">
                {navLinks.map((link) => {
                  const Icon = link.icon;
                  const isActive = location.pathname.startsWith(link.path);
                  return (
                    <Link
                      key={link.path}
                      to={link.path}
                      onClick={() => setIsMobileMenuOpen(false)}
                      className={`flex items-center gap-3 px-4 py-3 rounded-xl font-bold transition-all ${
                        isActive 
                          ? 'bg-gwf-primary/10 text-gwf-primary' 
                          : 'text-gwf-muted hover:text-gwf-primary hover:bg-gwf-primary/5'
                      }`}
                    >
                      <Icon size={20} /> {link.name}
                    </Link>
                  );
                })}
              </nav>

              <button 
                onClick={handleLogout}
                className="mt-auto flex items-center gap-3 px-4 py-3 text-gwf-error hover:bg-gwf-error/5 rounded-xl font-bold transition-all"
              >
                <LogOut size={20} /> Logout
              </button>
            </motion.aside>
          </>
        )}
      </AnimatePresence>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col min-w-0">
        <header className="h-16 bg-white border-b border-gwf-border flex items-center justify-between px-6 sticky top-0 z-30">
          <div className="flex items-center gap-4">
            <button 
              onClick={() => setIsMobileMenuOpen(true)}
              className="p-2 text-gwf-muted md:hidden"
            >
              <Menu size={24} />
            </button>
            <h2 className="text-lg font-black italic text-gwf-text tracking-tight uppercase">{PageTitle}</h2>
          </div>

          <div className="flex items-center gap-4">
            <div className="hidden sm:flex flex-col items-end">
              <span className="text-sm font-black text-gwf-text italic">{user?.fullName}</span>
              <span className="text-[10px] font-bold text-gwf-muted uppercase tracking-widest">{user?.role}</span>
            </div>
            <div className="w-10 h-10 rounded-full border-2 border-gwf-primary overflow-hidden bg-gwf-bg">
              <img 
                src={user?.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${user?.fullName}`} 
                alt="Admin" 
                className="w-full h-full object-cover"
              />
            </div>
          </div>
        </header>

        <main className="flex-1 p-4 md:p-8 overflow-x-hidden">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
