// src/pages/Admin/AdminDashboard.tsx
import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { 
  Users, 
  PlayCircle, 
  FileText, 
  AlertCircle,
  ChevronRight,
  TrendingUp,
  Award,
  Zap,
  Clock,
  Flame
} from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { collection, query, getDocs, orderBy, limit } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { useAuth } from '@/lib/AuthContext';
import { Session } from '@/types';
import { DUMMY_SESSIONS } from '@/data/dummy/session.dummy';
import { DUMMY_USERS } from '@/data/dummy/user.dummy';

export default function AdminDashboard() {
  const { isDemo, logout } = useAuth();
  const navigate = useNavigate();
  const [stats, setStats] = useState({
    totalUsers: 0,
    activeSessions: 0,
    totalScripts: 0,
    totalMistakes: 0
  });
  const [recentSessions, setRecentSessions] = useState<Session[]>([]);
  const [grammarStats, setGrammarStats] = useState<{ tag: string, count: number }[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDashboardData = async () => {
      try {
        if (isDemo) {
          setStats({
            totalUsers: DUMMY_USERS.length,
            activeSessions: DUMMY_SESSIONS.length,
            totalScripts: 12,
            totalMistakes: 45
          });
          setRecentSessions(DUMMY_SESSIONS);
          setGrammarStats([
            { tag: "Have Been / Has Been", count: 78 },
            { tag: "Perfect Tense Usage", count: 45 },
            { tag: "Article Confusion (a/an)", count: 32 },
            { tag: "Sentence Structure", count: 28 }
          ]);
          return;
        }

        const [usersSnap, sessionsSnap, scriptsSnap, mistakesSnap] = await Promise.all([
          getDocs(collection(db, 'users')),
          getDocs(query(collection(db, 'sessions'), orderBy('createdDate', 'desc'), limit(10))),
          getDocs(collection(db, 'scripts')),
          getDocs(collection(db, 'mistakes'))
        ]);

        setStats({
          totalUsers: usersSnap.size,
          activeSessions: sessionsSnap.size,
          totalScripts: scriptsSnap.size,
          totalMistakes: mistakesSnap.size
        });

        setRecentSessions(sessionsSnap.docs.map(doc => ({ id: doc.id, ...doc.data() } as Session)));

        // Aggregate grammar tags from mistakes
        const mistakesData = mistakesSnap.docs.map(doc => doc.data());
        const tagsMap: Record<string, number> = {};
        mistakesData.forEach(m => {
          if (m.grammarTag) {
            tagsMap[m.grammarTag] = (tagsMap[m.grammarTag] || 0) + 1;
          }
        });
        
        const sortedTags = Object.entries(tagsMap)
          .map(([tag, count]) => ({ tag, count }))
          .sort((a, b) => b.count - a.count)
          .slice(0, 5);
        
        setGrammarStats(sortedTags);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchDashboardData();
  }, [isDemo]);

  if (loading) return (
    <div className="flex items-center justify-center min-h-[400px]">
      <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-gwf-primary"></div>
    </div>
  );

  return (
    <div className="space-y-8">
      {/* Stats Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <StatCard icon={<Users className="text-blue-500" />} label="Total Users" value={stats.totalUsers} color="bg-blue-50" />
        <StatCard icon={<PlayCircle className="text-orange-500" />} label="Sessions Played" value={stats.activeSessions} color="bg-orange-50" />
        <StatCard icon={<FileText className="text-green-500" />} label="Scripts Uploaded" value={stats.totalScripts} color="bg-green-50" />
        <StatCard icon={<AlertCircle className="text-red-500" />} label="Mistakes Recorded" value={stats.totalMistakes} color="bg-red-50" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Recent Activity */}
        <div className="lg:col-span-2 space-y-8">
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-black italic text-gwf-text">Recent Sync Cycles</h3>
              <Link to="/admin/reports" className="text-xs font-bold text-gwf-primary hover:underline">View All Operations</Link>
            </div>
            <div className="bg-white rounded-2xl border border-gwf-border shadow-sm overflow-hidden">
               {/* ... table content remains same ... */}
               <table className="w-full text-left">
                 <thead>
                   <tr className="bg-gwf-bg/50 border-b border-gwf-border">
                     <th className="px-6 py-4 text-[10px] font-black uppercase text-gwf-muted tracking-widest">Session</th>
                     <th className="px-6 py-4 text-[10px] font-black uppercase text-gwf-muted tracking-widest">Status</th>
                     <th className="px-6 py-4 text-[10px] font-black uppercase text-gwf-muted tracking-widest text-right">Action</th>
                   </tr>
                 </thead>
                 <tbody className="divide-y divide-gwf-border">
                   {recentSessions.map((session) => (
                     <tr key={session.id} className="hover:bg-gwf-bg/30 transition-colors">
                       <td className="px-6 py-4">
                         <div className="flex flex-col">
                           <span className="font-bold text-sm tracking-tight">{session.sessionName}</span>
                           <span className="text-[10px] text-gwf-muted uppercase font-black tracking-tighter">{session.sessionMode}</span>
                         </div>
                       </td>
                       <td className="px-6 py-4">
                         <span className={`px-2 py-0.5 rounded-full text-[9px] font-black uppercase ${
                           session.status === 'COMPLETED' ? 'bg-green-100 text-green-700' : 'bg-orange-100 text-orange-700'
                         }`}>
                           {session.status}
                         </span>
                       </td>
                       <td className="px-6 py-4 text-right">
                         <button 
                           onClick={() => navigate(`/admin/reports`)}
                           className="p-2 hover:bg-gwf-primary/10 rounded-lg text-gwf-primary transition-colors flex items-center justify-center ml-auto"
                           title="View Report"
                         >
                           <ChevronRight size={18} className="pointer-events-none" />
                         </button>
                       </td>
                     </tr>
                   ))}
                 </tbody>
               </table>
            </div>
          </div>

          {/* Member Engagement Leaderboard */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-black italic text-gwf-text">Engagement Leaders</h3>
              <Link to="/admin/users" className="text-xs font-bold text-gwf-primary hover:underline">Manage All Members</Link>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
               {DUMMY_USERS.filter(u => u.role !== 'ADMIN').sort((a,b) => b.totalPracticeHours - a.totalPracticeHours).slice(0, 4).map((user, idx) => (
                  <button 
                    key={user.id} 
                    className="bg-white p-4 rounded-2xl border border-gwf-border flex items-center justify-between hover:border-gwf-primary/20 hover:shadow-md transition-all cursor-pointer text-left w-full" 
                    onClick={() => navigate('/admin/users')}
                  >
                     <div className="flex items-center gap-3 pointer-events-none">
                        <div className="relative">
                           <img src={user.avatar} alt="" className="w-10 h-10 rounded-full border border-gwf-border" />
                           <div className="absolute -top-1 -right-1 w-4 h-4 bg-gwf-primary text-white text-[8px] flex items-center justify-center rounded-full font-black">
                              {idx + 1}
                           </div>
                        </div>
                        <div>
                           <p className="text-sm font-bold truncate max-w-[100px]">{user.fullName}</p>
                           <div className="flex items-center gap-2">
                              <span className="text-[9px] font-black uppercase text-gwf-muted flex items-center gap-0.5">
                                 <Clock size={8} /> {user.totalPracticeHours}h
                              </span>
                              <span className="text-[9px] font-black uppercase text-gwf-accent flex items-center gap-0.5">
                                 <Flame size={8} /> {user.dailyStreakCount}d
                              </span>
                           </div>
                        </div>
                     </div>
                     <TrendingUp size={16} className="text-gwf-success pointer-events-none" />
                  </button>
               ))}
            </div>
          </div>
        </div>

        {/* Common Mistakes */}
        <div className="space-y-4">
          <h3 className="text-lg font-black italic text-gwf-text">Weak Areas (Grammar)</h3>
          <div className="bg-white p-6 rounded-2xl border border-gwf-border shadow-sm space-y-6">
            {grammarStats.length > 0 ? (
              grammarStats.map((item, idx) => (
                <WeakArea 
                  key={item.tag} 
                  row={item.tag} 
                  value={item.count} 
                  color={idx === 0 ? "bg-gwf-primary" : idx === 1 ? "bg-gwf-accent" : "bg-gwf-warning"} 
                />
              ))
            ) : (
              <p className="text-center text-gwf-muted italic text-xs py-10">No mistakes data collected yet.</p>
            )}
            
            <div className="pt-4 border-t border-gwf-border">
              <p className="text-[10px] text-gwf-muted font-black uppercase italic text-center">Across all active syncs</p>
            </div>
          </div>

          {/* Quick Actions Card */}
          <div className="bg-gwf-primary p-6 rounded-3xl text-white space-y-4 shadow-xl">
            <h4 className="font-black italic">Quick Actions</h4>
            <div className="grid grid-cols-1 gap-2">
               <button 
                onClick={() => navigate('/admin/scripts/upload')}
                className="w-full py-3 bg-white/20 hover:bg-white/30 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all text-left px-4"
              >
                Upload New Script
              </button>
              <button 
                onClick={() => navigate('/admin/reports')}
                className="w-full py-3 bg-white/20 hover:bg-white/30 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all text-left px-4"
              >
                View Analytics
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function StatCard({ icon, label, value, color }: { icon: React.ReactNode, label: string, value: number, color: string }) {
  return (
    <div className="bg-white p-6 rounded-2xl border border-gwf-border shadow-sm flex flex-col gap-4">
      <div className={`p-3 rounded-2xl w-fit ${color}`}>
        {icon}
      </div>
      <div>
        <p className="text-3xl font-black italic tracking-tighter text-gwf-text">{value}</p>
        <p className="text-[10px] font-black uppercase text-gwf-muted tracking-widest">{label}</p>
      </div>
    </div>
  );
}

function WeakArea({ row, value, color }: { row: string, value: number, color: string }) {
  return (
    <div className="space-y-2">
      <div className="flex justify-between text-[10px] font-black uppercase tracking-tight">
        <span className="text-gwf-text">{row}</span>
        <span className="text-gwf-muted">{value} users</span>
      </div>
      <div className="h-2 bg-gwf-bg rounded-full overflow-hidden">
        <motion.div 
          initial={{ width: 0 }}
          animate={{ width: `${value}%` }}
          className={`h-full ${color}`}
        />
      </div>
    </div>
  );
}

// src/app/modules/admin/dashboard/admin-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Users, Play, AlertCircle, TrendingUp, ChevronRight } from 'lucide-angular';
import { AdminService, DashboardSummary } from '@core/services/admin.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  template: `
    <div class="p-8 space-y-8 animate-in fade-in duration-500">
      <div class="flex items-center justify-between">
        <h1 class="text-3xl font-black italic tracking-tighter uppercase text-ls-text">Command Center</h1>
        <div class="bg-blue-50 text-ls-primary px-4 py-2 rounded-full text-xs font-black uppercase tracking-widest border border-blue-100">
          Real-time Sync Active
        </div>
      </div>

      <!-- Stats Grid -->
      <div class="grid grid-cols-1 md:grid-cols-4 gap-6" *ngIf="summary$ | async as s">
        <div class="card flex flex-col gap-4">
          <div class="w-12 h-12 bg-blue-100 rounded-2xl flex items-center justify-center text-ls-primary">
            <i-lucide [img]="UsersIcon" size="24"></i-lucide>
          </div>
          <div>
            <p class="text-[10px] font-black uppercase tracking-widest text-ls-text-muted">Total Active Users</p>
            <p class="text-3xl font-black italic text-ls-text">{{ s.totalUsers }}</p>
          </div>
        </div>

        <div class="card flex flex-col gap-4">
          <div class="w-12 h-12 bg-green-100 rounded-2xl flex items-center justify-center text-ls-success">
            <i-lucide [img]="PlayIcon" size="24"></i-lucide>
          </div>
          <div>
            <p class="text-[10px] font-black uppercase tracking-widest text-ls-text-muted">Live Sessions</p>
            <p class="text-3xl font-black italic text-ls-text">{{ s.activeSessions }}</p>
          </div>
        </div>

        <div class="card flex flex-col gap-4">
          <div class="w-12 h-12 bg-orange-100 rounded-2xl flex items-center justify-center text-ls-accent">
            <i-lucide [img]="TrendIcon" size="24"></i-lucide>
          </div>
          <div>
            <p class="text-[10px] font-black uppercase tracking-widest text-ls-text-muted">Avg. Fluency Score</p>
            <p class="text-3xl font-black italic text-ls-text">84%</p>
          </div>
        </div>

        <div class="card flex flex-col gap-4">
          <div class="w-12 h-12 bg-red-100 rounded-2xl flex items-center justify-center text-ls-error">
            <i-lucide [img]="AlertIcon" size="24"></i-lucide>
          </div>
          <div>
            <p class="text-[10px] font-black uppercase tracking-widest text-ls-text-muted">Pending Correction Rounds</p>
            <p class="text-3xl font-black italic text-ls-text">42</p>
          </div>
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <!-- Recent Activity -->
        <div class="lg:col-span-2 space-y-4">
          <h3 class="text-xs font-black uppercase tracking-[0.2em] text-ls-text-muted px-2">Live Activity Stream</h3>
          <div class="card p-0 overflow-hidden">
             <div class="divide-y divide-ls-card-border" *ngIf="summary$ | async as s">
                <div *ngFor="let item of s.recentActivity" class="p-5 flex items-center justify-between hover:bg-ls-bg transition-colors group cursor-pointer">
                   <div class="flex items-center gap-4">
                      <div class="w-10 h-10 bg-ls-bg rounded-xl border border-ls-card-border overflow-hidden">
                         <img [src]="'https://api.dicebear.com/7.x/avataaars/svg?seed=' + item.user" alt="avatar">
                      </div>
                      <div>
                        <p class="text-sm font-bold text-ls-text">{{ item.user }}</p>
                        <p class="text-xs text-ls-text-muted">{{ item.action }}</p>
                      </div>
                   </div>
                   <div class="flex items-center gap-4">
                      <span class="text-[10px] font-black text-ls-text-muted uppercase italic">{{ item.time }}</span>
                      <i-lucide [img]="ChevronIcon" size="16" class="text-ls-card-border group-hover:text-ls-primary group-hover:translate-x-1 transition-all"></i-lucide>
                   </div>
                </div>
             </div>
          </div>
        </div>

        <!-- Top Mistakes -->
        <div class="space-y-4">
          <h3 class="text-xs font-black uppercase tracking-[0.2em] text-ls-text-muted px-2">Top Learning Gaps</h3>
          <div class="card space-y-6" *ngIf="summary$ | async as s">
             <div *ngFor="let m of s.topMistakes" class="space-y-2">
                <div class="flex items-center justify-between">
                   <span class="text-[10px] font-black uppercase tracking-widest text-ls-text">{{ m.type }}</span>
                   <span class="text-[10px] font-bold text-ls-accent italic">{{ m.count }} occurrences</span>
                </div>
                <div class="h-2 bg-ls-bg rounded-full overflow-hidden">
                   <div class="h-full bg-ls-primary rounded-full transition-all duration-1000" [style.width.%]="m.count * 2"></div>
                </div>
             </div>
             
             <button class="w-full py-4 text-[10px] font-black uppercase tracking-[0.2em] text-ls-primary hover:bg-blue-50 rounded-xl transition-all border border-transparent hover:border-blue-100">
               Generate detailed report
             </button>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: []
})
export class AdminDashboardComponent implements OnInit {
  readonly UsersIcon = Users;
  readonly PlayIcon = Play;
  readonly AlertIcon = AlertCircle;
  readonly TrendIcon = TrendingUp;
  readonly ChevronIcon = ChevronRight;

  summary$!: Observable<DashboardSummary>;

  constructor(private adminService: AdminService) {}

  ngOnInit() {
    this.summary$ = this.adminService.getDashboardSummary();
  }
}

<div class="dashboard-page space-y-7">

  <div class="stats-grid">
    <div class="stat-card blue">
      <div class="stat-card-header">
        <div class="stat-icon blue">
          <i-lucide [img]="UsersIcon" size="20"></i-lucide>
        </div>
      </div>
      <div>
        <div class="stat-value">{{ stats()?.[0]?.value ?? '—' }}</div>
        <div class="stat-label">Total Users</div>
      </div>
    </div>

    <div class="stat-card orange">
      <div class="stat-card-header">
        <div class="stat-icon orange">
          <i-lucide [img]="SessionIcon" size="20"></i-lucide>
        </div>
        <div class="live-badge">Live</div>
      </div>
      <div>
        <div class="stat-value">{{ stats()?.[1]?.value ?? '—' }}</div>
        <div class="stat-label">Active Sessions</div>
      </div>
    </div>

    <div class="stat-card green">
      <div class="stat-card-header">
        <div class="stat-icon green">
          <i-lucide [img]="FileTextIcon" size="20"></i-lucide>
        </div>
      </div>
      <div>
        <div class="stat-value">{{ stats()?.[2]?.value ?? '—' }}</div>
        <div class="stat-label">Total Scripts</div>
      </div>
    </div>

    <div class="stat-card red">
      <div class="stat-card-header">
        <div class="stat-icon red">
          <i-lucide [img]="AlertIcon" size="20"></i-lucide>
        </div>
      </div>
      <div>
        <div class="stat-value">{{ stats()?.[3]?.value ?? '—' }}</div>
        <div class="stat-label">Mistakes Recorded</div>
      </div>
    </div>
  </div>

  <div class="dashboard-lower">
    <div class="section-card">
      <div class="section-header">
        <h3 class="section-title">Recent Sessions</h3>
        <a routerLink="/admin/reports" style="font-size: 13px; font-weight: 600; color: var(--gwf-primary); text-decoration: none; display: flex; align-items: center; gap: 4px;">
          View All <i-lucide [img]="ArrowIcon" size="14"></i-lucide>
        </a>
      </div>

      @if (recentActivity().length === 0) {
        <div class="empty-state">No recent sessions yet.</div>
      } @else {
        <table mat-table [dataSource]="recentActivity()" class="w-full">
          <ng-container matColumnDef="user">
            <th mat-header-cell *matHeaderCellDef> USER </th>
            <td mat-cell *matCellDef="let element" style="font-weight: 600;">
              <div style="display: flex; align-items: center; gap: 8px;">
                <div style="width: 28px; height: 28px; border-radius: 6px; background: var(--gwf-primary); color: white; display: flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 700;">
                  {{ initials(element.userName) }}
                </div>
                {{element.userName}}
              </div>
            </td>
          </ng-container>

          <ng-container matColumnDef="session">
            <th mat-header-cell *matHeaderCellDef class="hidden md:table-cell"> SESSION </th>
            <td mat-cell *matCellDef="let element" class="hidden md:table-cell" style="color: var(--gwf-text-muted);">
              {{element.sessionName}}
            </td>
          </ng-container>

          <ng-container matColumnDef="fluency">
            <th mat-header-cell *matHeaderCellDef> FLUENCY </th>
            <td mat-cell *matCellDef="let element" style="font-weight: 700; color: var(--gwf-success);">
              {{element.fluencyScore}}%
            </td>
          </ng-container>

          <ng-container matColumnDef="status">
            <th mat-header-cell *matHeaderCellDef> STATUS </th>
            <td mat-cell *matCellDef="let element">
              <span class="badge" [ngClass]="element.status === 'COMPLETED' ? 'badge-success' : 'badge-warning'">
                {{element.status}}
              </span>
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="['user', 'session', 'fluency', 'status']"></tr>
          <tr mat-row *matRowDef="let row; columns: ['user', 'session', 'fluency', 'status'];"></tr>
        </table>
      }
    </div>

    <div class="section-card">
      <div class="section-header">
        <h3 class="section-title">Weak Areas</h3>
      </div>
      <div style="padding: 10px 0;">
        @if (weakAreas().length === 0) {
          <div class="empty-state">No weak area data yet.</div>
        } @else {
          @for (area of weakAreas(); track area.tag; let i = $index) {
            <div class="weak-area-item">
              <div class="weak-area-label">
                <span><span style="color: var(--gwf-text-muted); margin-right: 8px;">#{{i + 1}}</span>{{area.tag}}</span>
                <span style="font-size: 11px; color: var(--gwf-warning); background: rgba(245, 158, 11, 0.1); padding: 2px 8px; border-radius: 10px;">{{area.count}} users</span>
              </div>
              <div class="weak-area-bar-bg">
                <div class="weak-area-bar-fill" [style.width.%]="area.percentage"></div>
              </div>
            </div>
          }
        }
      </div>
    </div>
  </div>

  <div>
    <h3 style="font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: var(--gwf-text); margin-bottom: 16px;">Quick Actions</h3>
    <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px;">
      <a mat-stroked-button color="primary" routerLink="/admin/scripts" style="height: 48px; font-weight: 600;">
        <mat-icon>upload</mat-icon> Upload Script
      </a>
      <a mat-stroked-button routerLink="/admin/reports" style="height: 48px; font-weight: 600;">
        <mat-icon>bar_chart</mat-icon> View Reports
      </a>
      <button mat-stroked-button (click)="onAddUser()" style="height: 48px; font-weight: 600;">
        <mat-icon>person_add</mat-icon> Add User
      </button>
    </div>
  </div>
</div>
