// src/app/modules/user/profile/profile.component.ts
// File: src/app/modules/user/profile/profile.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { UserService } from '@core/services/user.service';
import { UserProfile } from '@core/models/user.model';
import { LucideAngularModule, User, Mail, Smartphone, Calendar, Award, Target, Flame, Edit2, LogOut, Camera, Check } from 'lucide-angular';
import { AuthService } from '@core/services/auth.service';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { ToastService } from '@core/services/toast.service';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [CommonModule, LucideAngularModule, ReactiveFormsModule],
  template: `
    <div class="space-y-10 animate-in fade-in duration-500 pb-32">
      <!-- Profile Header -->
      <div class="flex flex-col items-center gap-6 relative">
         <div class="relative group">
            <div class="w-32 h-32 rounded-[48px] overflow-hidden border-4 border-white shadow-xl bg-gw-bg">
               <img [src]="profile()?.avatar || 'https://api.dicebear.com/7.x/avataaars/svg?seed=' + profile()?.fullName" class="w-full h-full object-cover">
            </div>
            <label class="absolute -bottom-2 -right-2 w-10 h-10 bg-gw-primary text-white rounded-2xl flex items-center justify-center cursor-pointer shadow-lg hover:scale-110 active:scale-95 transition-all">
               <i-lucide [img]="CameraIcon" size="18"></i-lucide>
               <input type="file" class="hidden" (change)="onAvatarChange($event)">
            </label>
         </div>

         <div class="text-center space-y-2">
            @if (!isEditing()) {
              <div class="flex items-center justify-center gap-3">
                 <h2 class="text-3xl font-black text-gw-text italic uppercase tracking-tighter">{{ profile()?.fullName }}</h2>
                 <button (click)="toggleEdit()" class="text-gw-text-muted hover:text-gw-primary transition-colors">
                    <i-lucide [img]="EditIcon" size="18"></i-lucide>
                 </button>
              </div>
            } @else {
              <div class="flex flex-col gap-4">
                 <form [formGroup]="editForm" (ngSubmit)="saveProfile()" class="space-y-4">
                    <input 
                      formControlName="fullName"
                      class="w-full h-12 bg-white border-2 border-gw-card-border rounded-xl px-4 text-lg font-bold italic focus:border-gw-primary outline-none text-center"
                      placeholder="Full Name"
                    >
                    <div class="flex gap-2">
                       <button type="button" (click)="toggleEdit()" class="flex-1 h-10 border border-gw-card-border rounded-xl text-[10px] font-black uppercase tracking-widest text-gw-text-muted">Cancel</button>
                       <button type="submit" [disabled]="editForm.invalid || isLoading()" class="flex-1 h-10 bg-gw-primary text-white rounded-xl text-[10px] font-black uppercase tracking-widest flex items-center justify-center gap-2">
                          @if (isLoading()) { <div class="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"></div> }
                          Save
                       </button>
                    </div>
                 </form>
              </div>
            }
            <div class="flex gap-2 justify-center">
               <span class="px-3 py-1 bg-gw-accent/10 text-gw-accent rounded-lg text-[8px] font-black uppercase tracking-widest italic">{{ profile()?.ageGroup }}</span>
               <span class="px-3 py-1 bg-gw-primary/10 text-gw-primary rounded-lg text-[8px] font-black uppercase tracking-widest italic">{{ profile()?.preferredHintLanguage }} Hint</span>
               <span class="px-3 py-1 bg-[#F59E0B]/10 text-[#F59E0B] rounded-lg text-[8px] font-black uppercase tracking-widest italic flex items-center gap-1">
                  <i-lucide [img]="FlameIcon" size="10"></i-lucide>
                  {{ profile()?.dailyStreakCount }} Streak
               </span>
            </div>
         </div>
      </div>

      <!-- Quick Stats -->
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        @for (stat of stats; track stat.label) {
          <div class="bg-white p-6 rounded-[32px] border border-gw-card-border shadow-sm space-y-1">
             <span class="text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">{{ stat.label }}</span>
             <p class="text-2xl font-black text-gw-text italic">{{ stat.value }}</p>
          </div>
        }
      </div>

      <!-- Account Info -->
      <div class="bg-white p-8 rounded-[40px] border border-gw-card-border shadow-sm space-y-8">
         <div class="flex items-center gap-4 text-gw-text-muted">
            <div class="w-10 h-10 bg-gw-bg rounded-xl flex items-center justify-center">
               <i-lucide [img]="SmartphoneIcon" size="18"></i-lucide>
            </div>
            <div class="flex-1">
               <p class="text-[8px] font-black uppercase tracking-widest italic">Mobile Number</p>
               <p class="font-bold italic">{{ profile()?.mobileNumber }}</p>
            </div>
         </div>

         <div class="flex items-center gap-4 text-gw-text-muted">
            <div class="w-10 h-10 bg-gw-bg rounded-xl flex items-center justify-center">
               <i-lucide [img]="MailIcon" size="18"></i-lucide>
            </div>
            <div class="flex-1">
               <p class="text-[8px] font-black uppercase tracking-widest italic">Email Address</p>
               <p class="font-bold italic">{{ profile()?.email || 'Not provided' }}</p>
            </div>
         </div>

         <div class="flex items-center gap-4 text-gw-text-muted">
            <div class="w-10 h-10 bg-gw-bg rounded-xl flex items-center justify-center">
               <i-lucide [img]="CalendarIcon" size="18"></i-lucide>
            </div>
            <div class="flex-1">
               <p class="text-[8px] font-black uppercase tracking-widest italic">Member Since</p>
               <p class="font-bold italic">{{ profile()?.registrationDate | date:'MMMM yyyy' }}</p>
            </div>
         </div>
      </div>

      <!-- Preferences -->
      <div class="space-y-6">
        <h3 class="text-lg font-black text-gw-text italic uppercase tracking-widest border-l-4 border-gw-accent pl-4">Update Preferences</h3>
        <div class="grid gap-4">
           <div class="bg-white p-6 rounded-3xl border border-gw-card-border flex items-center justify-between">
              <span class="text-xs font-bold text-gw-text-muted uppercase tracking-widest italic">Hint Language</span>
              <select 
                [value]="profile()?.preferredHintLanguage"
                (change)="updatePreference('preferredHintLanguage', $any($event.target).value)"
                class="bg-gw-bg px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest border-none outline-none"
              >
                 <option value="Telugu">Telugu</option>
                 <option value="Hindi">Hindi</option>
                 <option value="Tamil">Tamil</option>
                 <option value="Kannada">Kannada</option>
                 <option value="None">None</option>
              </select>
           </div>
           
           <div class="bg-white p-6 rounded-3xl border border-gw-card-border flex items-center justify-between">
              <span class="text-xs font-bold text-gw-text-muted uppercase tracking-widest italic">Age Group</span>
              <select 
                [value]="profile()?.ageGroup"
                (change)="updatePreference('ageGroup', $any($event.target).value)"
                class="bg-gw-bg px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest border-none outline-none"
              >
                 <option value="Child (6-12)">Child (6-12)</option>
                 <option value="Teen (13-17)">Teen (13-17)</option>
                 <option value="Adult (18+)">Adult (18+)</option>
              </select>
           </div>
        </div>
      </div>

      <!-- Actions -->
      <div class="pt-6">
         <button 
           (click)="logout()"
           class="w-full h-16 border-2 border-gw-error text-gw-error font-black uppercase tracking-widest italic rounded-2xl flex items-center justify-center gap-3 hover:bg-gw-error hover:text-white transition-all shadow-lg shadow-gw-error/5"
         >
            <i-lucide [img]="LogoutIcon" size="20"></i-lucide>
            Log Out
         </button>
      </div>

      <!-- Hidden File Input for Avatar is handled via label -->
    </div>
  `,
  styles: [`
    :host { display: block; }
  `]
})
export class ProfileComponent implements OnInit {
  private userService = inject(UserService);
  private authService = inject(AuthService);
  private fb = inject(FormBuilder);
  private toast = inject(ToastService);

  readonly CameraIcon = Camera;
  readonly EditIcon = Edit2;
  readonly FlameIcon = Flame;
  readonly SmartphoneIcon = Smartphone;
  readonly MailIcon = Mail;
  readonly CalendarIcon = Calendar;
  readonly LogoutIcon = LogOut;

  profile = signal<UserProfile | null>(null);
  isEditing = signal(false);
  isLoading = signal(false);
  stats: any[] = [];

  editForm = this.fb.group({
    fullName: ['', [Validators.required, Validators.minLength(2)]]
  });

  ngOnInit() {
    this.loadProfile();
  }

  loadProfile() {
    this.userService.getProfile().subscribe(res => {
      this.profile.set(res);
      this.editForm.patchValue({ fullName: res.fullName });
      this.stats = [
        { label: 'Sessions', value: res.totalSessionsPlayed },
        { label: 'Avg Fluency', value: res.avgFluencyScore + '%' },
        { label: 'Mistakes Fixed', value: res.mistakesFixed },
        { label: 'Streak', value: res.dailyStreakCount }
      ];
    });
  }

  toggleEdit() {
    this.isEditing.set(!this.isEditing());
  }

  saveProfile() {
    if (this.editForm.invalid) return;
    this.isLoading.set(true);
    const fullName = this.editForm.value.fullName as string;
    
    this.userService.updateProfile({ fullName }).subscribe({
      next: (res) => {
        this.profile.set(res);
        this.isEditing.set(false);
        this.isLoading.set(false);
        this.toast.success('Profile updated successfully');
      },
      error: () => this.isLoading.set(false)
    });
  }

  onAvatarChange(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.isLoading.set(true);
      this.userService.uploadAvatar(file).subscribe({
        next: (res) => {
          this.profile.update(p => p ? ({ ...p, avatar: res.avatarUrl }) : null);
          this.isLoading.set(false);
          this.toast.success('Avatar updated');
        },
        error: () => this.isLoading.set(false)
      });
    }
  }

  updatePreference(key: string, value: any) {
    this.userService.updateProfile({ [key]: value }).subscribe(res => {
      this.profile.set(res);
      this.toast.success('Preference updated');
    });
  }

  logout() {
    this.authService.logout();
  }
}

// src/pages/User/Profile.tsx
import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { 
  User as UserIcon, 
  Settings, 
  LogOut, 
  CheckCircle2, 
  Flame, 
  TrendingUp, 
  AlertCircle,
  Camera,
  ChevronRight,
  Globe,
  Bell,
  Smartphone,
  Calendar,
  X,
  Target
} from 'lucide-react';
import { useAuth } from '@/lib/AuthContext';
import { userService } from '@/lib/userService';
import { useNavigate } from 'react-router-dom';
import { User } from '@/types';

const AVATARS = [
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Jasper',
  'https://api.dicebear.com/7.x/avataaars/svg?seed=Luna'
];

export default function Profile() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const [profile, setProfile] = useState<User | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [formData, setFormData] = useState({
    fullName: '',
    ageGroup: '',
    hintLanguage: '',
    avatar: ''
  });
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (user) {
      setProfile(user as User);
      setFormData({
        fullName: user.fullName || '',
        ageGroup: user.ageGroup || 'Adult (18+)',
        hintLanguage: user.preferredHintLanguage || 'Telugu',
        avatar: user.avatar || AVATARS[0]
      });
    }
  }, [user]);

  const handleSave = async () => {
    if (!user) return;
    setSaving(true);
    try {
      await userService.updateProfile(user.id, {
        fullName: formData.fullName,
        ageGroup: formData.ageGroup as any,
        preferredHintLanguage: formData.hintLanguage,
        avatar: formData.avatar
      });
      setIsEditing(false);
      window.location.reload(); // Refresh to update auth context
    } catch (err) {
      console.error(err);
    } finally {
      setSaving(false);
    }
  };

  if (!user || !profile) return null;

  return (
    <div className="min-h-screen bg-gwf-bg pb-24">
      <header className="p-6 bg-white border-b border-gwf-border sticky top-0 z-10 flex items-center justify-between">
         <div className="flex items-center gap-3">
            <button onClick={() => navigate(-1)} className="p-2 hover:bg-gwf-bg rounded-xl transition-all">
               <ChevronRight size={20} className="rotate-180 text-gwf-muted" />
            </button>
            <h1 className="text-xl font-black italic tracking-tight">Sync Identity</h1>
         </div>
         <button onClick={() => navigate('/user/notifications')} className="p-2 hover:bg-gwf-bg rounded-xl transition-all">
            <Bell size={20} className="text-gwf-muted" />
         </button>
      </header>

      <main className="max-w-xl mx-auto p-6 space-y-8">
        {/* Profile Header */}
        <div className="flex flex-col items-center gap-6 text-center">
           <div className="relative">
              <div className="w-24 h-24 rounded-[32px] border-4 border-gwf-primary/20 p-1 bg-white shadow-xl">
                 <img src={formData.avatar} className="w-full h-full object-cover rounded-[24px]" alt="Avatar" />
              </div>
              <button 
                onClick={() => setIsEditing(true)}
                className="absolute -bottom-2 -right-2 p-2 bg-gwf-primary text-white rounded-xl shadow-lg shadow-gwf-primary/30 active:scale-95 transition-all"
              >
                 <Camera size={16} />
              </button>
           </div>
           
           <div className="space-y-1">
              <h2 className="text-2xl font-black italic">{profile.fullName}</h2>
              <p className="text-xs text-gwf-muted font-bold tracking-widest uppercase">{profile.email}</p>
           </div>

           <div className="flex gap-2">
              <span className="px-3 py-1 bg-gwf-primary/10 text-gwf-primary text-[9px] font-black uppercase rounded-lg border border-gwf-primary/20">
                 {profile.ageGroup}
              </span>
              <span className="px-3 py-1 bg-gwf-accent/10 text-gwf-accent text-[9px] font-black uppercase rounded-lg border border-gwf-accent/20">
                 {profile.preferredHintLanguage} Sync
              </span>
              <div className="px-3 py-1 bg-gwf-secondary/10 text-gwf-secondary text-[9px] font-black uppercase rounded-lg border border-gwf-secondary/20 flex items-center gap-1">
                 <Flame size={10} /> 7 Day Streak
              </div>
           </div>
        </div>

        {/* Edit Form */}
        {isEditing && (
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="card-base space-y-6"
          >
             <div className="flex items-center justify-between">
                <h3 className="text-sm font-black italic uppercase text-gwf-muted">Edit Sync Profile</h3>
                <button onClick={() => setIsEditing(false)}><X size={18} className="text-gwf-muted" /></button>
             </div>

             <div className="space-y-4">
                <div className="space-y-2">
                   <label className="text-[10px] font-black uppercase tracking-widest text-gwf-muted">Choose Avatar</label>
                   <div className="flex gap-4">
                      {AVATARS.map((av) => (
                        <button 
                          key={av} 
                          onClick={() => setFormData(prev => ({ ...prev, avatar: av }))}
                          className={`w-12 h-12 rounded-xl border-2 transition-all ${formData.avatar === av ? 'border-gwf-primary p-0.5' : 'border-transparent opacity-40'}`}
                        >
                           <img src={av} className="w-full h-full object-cover rounded-lg" />
                        </button>
                      ))}
                   </div>
                </div>

                <div className="space-y-2">
                   <label className="text-[10px] font-black uppercase tracking-widest text-gwf-muted">Full Name</label>
                   <input 
                      type="text"
                      className="gwf-input"
                      value={formData.fullName}
                      onChange={(e) => setFormData(prev => ({ ...prev, fullName: e.target.value }))}
                   />
                </div>

                <div className="grid grid-cols-2 gap-4">
                   <div className="space-y-2">
                      <label className="text-[10px] font-black uppercase tracking-widest text-gwf-muted">Sync Hint Language</label>
                      <select 
                        className="gwf-input"
                        value={formData.hintLanguage}
                        onChange={(e) => setFormData(prev => ({ ...prev, hintLanguage: e.target.value }))}
                      >
                         <option>Telugu</option>
                         <option>Hindi</option>
                         <option>Kannada</option>
                         <option>Tamil</option>
                      </select>
                   </div>
                   <div className="space-y-2">
                      <label className="text-[10px] font-black uppercase tracking-widest text-gwf-muted">Age Group</label>
                      <select 
                        className="gwf-input"
                        value={formData.ageGroup}
                        onChange={(e) => setFormData(prev => ({ ...prev, ageGroup: e.target.value }))}
                      >
                         <option>Under 18</option>
                         <option>18-24</option>
                         <option>25-34</option>
                         <option>35+</option>
                      </select>
                   </div>
                </div>

                <button 
                  onClick={handleSave}
                  disabled={saving}
                  className="btn-primary w-full h-12 rounded-2xl flex items-center justify-center gap-2"
                >
                   {saving ? 'Syncing...' : 'Save Profile Changes'} <CheckCircle2 size={18} />
                </button>
             </div>
          </motion.div>
        )}

        {/* Stats Section */}
        <div className="grid grid-cols-2 gap-4">
           <AccountStat label="Total Syncs" value={14} icon={<Target size={14} />} />
           <AccountStat label="Avg Fluency" value="82%" icon={<TrendingUp size={14} />} />
           <AccountStat label="Mistakes Refined" value={54} icon={<AlertCircle size={14} />} />
           <AccountStat label="Member Since" value="May 2024" icon={<Calendar size={14} />} />
        </div>

        {/* Settings Links */}
        <div className="space-y-3">
           <p className="text-[10px] font-black uppercase tracking-widest text-gwf-muted px-2">Learning Progress</p>
           <div className="bg-white border border-gwf-border rounded-[32px] overflow-hidden mb-4">
              <SettingsLink 
                icon={<TrendingUp size={18} />} 
                label="Fluency Analytics" 
                onClick={() => navigate('/user/progress')}
              />
              <SettingsLink 
                icon={<AlertCircle size={18} />} 
                label="Mistake Bank" 
                onClick={() => navigate('/user/mistakes')}
              />
              <SettingsLink 
                icon={<Target size={18} />} 
                label="My Learning Syncs" 
                onClick={() => navigate('/user/sessions')}
              />
           </div>

           <p className="text-[10px] font-black uppercase tracking-widest text-gwf-muted px-2">Account Settings</p>
           <div className="bg-white border border-gwf-border rounded-[32px] overflow-hidden">
              <SettingsLink icon={<Bell size={18} />} label="Notifications" onClick={() => navigate('/user/notifications')} />
              <SettingsLink icon={<Globe size={18} />} label="App Language" value="English" />
              <SettingsLink icon={<Smartphone size={18} />} label="Mobile Number" value="+91 98*** **456" />
           </div>
        </div>

        <button 
           onClick={() => logout()}
           className="w-full h-14 rounded-2xl border-2 border-gwf-error/20 text-gwf-error font-black italic text-lg flex items-center justify-center gap-2 hover:bg-gwf-error/5 transition-all"
        >
           <LogOut size={20} /> Logout
        </button>
      </main>
    </div>
  );
}

function AccountStat({ label, value, icon }: { label: string, value: string | number, icon: React.ReactNode }) {
  return (
    <div className="card-base py-5 flex flex-col gap-2">
       <div className="flex items-center gap-2 text-gwf-muted">
          {icon}
          <span className="text-[8px] font-black uppercase tracking-widest">{label}</span>
       </div>
       <p className="text-xl font-black italic">{value}</p>
    </div>
  );
}

function SettingsLink({ icon, label, value, onClick }: { icon: React.ReactNode, label: string, value?: string, onClick?: () => void }) {
  return (
    <button 
      onClick={onClick}
      className="w-full p-5 flex items-center justify-between border-b border-gwf-border last:border-b-0 hover:bg-gwf-bg transition-all"
    >
       <div className="flex items-center gap-4">
          <div className="text-gwf-primary opacity-60">{icon}</div>
          <span className="text-sm font-bold">{label}</span>
       </div>
       <div className="flex items-center gap-2">
          {value && <span className="text-xs text-gwf-muted font-medium">{value}</span>}
          <ChevronRight size={14} className="text-gwf-muted" />
       </div>
    </button>
  );
}
