// src/app/modules/session/session-detail/session-detail.component.ts
// File: src/app/modules/session/session-detail/session-detail.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { UserService } from '@core/services/user.service';
import { RepracticeService } from '../../repractice/repractice.service';
import { SessionDetail } from '@core/models/session.model';
import { LucideAngularModule, ChevronLeft, Calendar, Clock, Award, Target, Zap, RotateCcw, BookOpen, User, ArrowRight, Info } from 'lucide-angular';
import { ToastService } from '@core/services/toast.service';

@Component({
  selector: 'app-session-detail',
  standalone: true,
  imports: [CommonModule, LucideAngularModule, RouterLink],
  template: `
    <div class="space-y-8 animate-in slide-in-from-bottom-10 duration-700 pb-32">
      <!-- Header -->
      <div class="flex items-center gap-4">
         <button routerLink="/user/dashboard" class="w-10 h-10 rounded-xl bg-gw-bg flex items-center justify-center text-gw-text-muted hover:text-gw-primary transition-all">
            <i-lucide [img]="BackIcon" size="20"></i-lucide>
         </button>
         <div>
            <h2 class="text-2xl font-black text-gw-text italic uppercase tracking-tighter">{{ detail()?.sessionName }}</h2>
            <p class="text-[10px] font-bold text-gw-text-muted uppercase tracking-widest italic">{{ detail()?.createdDate | date:'fullDate' }}</p>
         </div>
      </div>

      <!-- Performance Overview -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
         <!-- Circular Progress + Main Stats -->
         <div class="bg-white p-8 rounded-[40px] border border-gw-card-border shadow-sm flex flex-col items-center gap-8">
            <div class="relative w-48 h-48 flex items-center justify-center">
               <svg class="w-full h-full -rotate-90">
                  <circle cx="96" cy="96" r="88" fill="none" stroke="currentColor" stroke-width="12" class="text-gw-bg"></circle>
                  <circle cx="96" cy="96" r="88" fill="none" stroke="currentColor" stroke-width="12" 
                    [style.stroke-dasharray]="553" 
                    [style.stroke-dashoffset]="553 - (553 * (detail()?.myPerformance?.fluency || 0) / 100)"
                    class="transition-all duration-1000 ease-out"
                    [class.text-gw-success]="(detail()?.myPerformance?.fluency || 0) >= 80"
                    [class.text-[#F59E0B]]="(detail()?.myPerformance?.fluency || 0) < 80 && (detail()?.myPerformance?.fluency || 0) >= 60"
                    [class.text-gw-error]="(detail()?.myPerformance?.fluency || 0) < 60"
                  ></circle>
               </svg>
               <div class="absolute inset-0 flex flex-col items-center justify-center text-center">
                  <span class="text-[10px] font-black uppercase tracking-widest text-gw-text-muted italic">Fluency Score</span>
                  <p class="text-4xl font-black italic">{{ detail()?.myPerformance?.fluency }}%</p>
               </div>
            </div>

            <div class="grid grid-cols-3 w-full gap-4 border-t border-gw-bg pt-8">
               <div class="text-center space-y-1">
                  <span class="text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">Confidence</span>
                  <p class="text-lg font-black italic">{{ detail()?.myPerformance?.confidence }}%</p>
               </div>
               <div class="text-center space-y-1 border-x border-gw-bg">
                  <span class="text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">Speed</span>
                  <p class="text-lg font-black italic">{{ detail()?.myPerformance?.speedWpm }}<span class="text-[10px] ml-0.5">wpm</span></p>
               </div>
               <div class="text-center space-y-1">
                  <span class="text-[8px] font-black uppercase tracking-widest text-gw-text-muted italic">Pauses</span>
                  <p class="text-lg font-black italic">{{ detail()?.myPerformance?.pauses }}</p>
               </div>
            </div>
         </div>

         <!-- Listener Feedback + Session Info -->
         <div class="space-y-6">
            <div class="bg-white p-8 rounded-[40px] border border-gw-card-border shadow-sm space-y-6">
               <h3 class="text-xs font-black uppercase tracking-widest text-gw-text-muted italic flex items-center gap-2">
                  <i-lucide [img]="AwardIcon" size="14"></i-lucide>
                  LISTENER FEEDBACK
               </h3>
               <div class="grid grid-cols-2 gap-4">
                  @for (fb of detail()?.listenerFeedback; track fb.tag) {
                    <div class="p-4 bg-gw-bg rounded-2xl border border-gw-bg flex items-center justify-between">
                       <span class="text-[10px] font-bold text-gw-text italic">{{ fb.tag }}</span>
                       <span class="px-2 py-0.5 bg-white rounded-lg text-[10px] font-black text-gw-primary">{{ fb.count }}</span>
                    </div>
                  }
               </div>
            </div>

            <div class="bg-[#1A1A2E] p-8 rounded-[40px] shadow-sm space-y-6 text-white">
               <h3 class="text-xs font-black uppercase tracking-widest text-white/40 italic flex items-center gap-2">
                  <i-lucide [img]="InfoIcon" size="14"></i-lucide>
                  SESSION CONTEXT
               </h3>
               <div class="space-y-4">
                  <div class="flex justify-between items-center text-[10px]">
                     <span class="font-bold text-white/40 uppercase tracking-widest italic">Script</span>
                     <span class="font-black italic text-gw-accent">{{ detail()?.scriptTitle }}</span>
                  </div>
                  <div class="flex justify-between items-center text-[10px]">
                     <span class="font-bold text-white/40 uppercase tracking-widest italic">Mode</span>
                     <span class="font-black italic">{{ detail()?.sessionMode }}</span>
                  </div>
                  <div class="flex justify-between items-center text-[10px]">
                     <span class="font-bold text-white/40 uppercase tracking-widest italic">Duration</span>
                     <span class="font-black italic">{{ detail()?.sessionDuration }} min</span>
                  </div>
               </div>
            </div>
         </div>
      </div>

      <!-- My Mistakes Section -->
      <div class="space-y-6">
         <div class="flex items-center justify-between">
            <h3 class="text-lg font-black text-gw-text italic uppercase tracking-widest border-l-4 border-gw-error pl-4">Mistakes to Fix</h3>
            <span class="text-[10px] font-black bg-gw-error/10 text-gw-error px-3 py-1 rounded-full italic">{{ detail()?.myMistakes?.length }} DETECTED</span>
         </div>

         <div class="grid gap-4">
            @for (mistake of detail()?.myMistakes; track mistake.said) {
               <div class="bg-white p-6 rounded-[32px] border border-gw-card-border shadow-sm space-y-6 group">
                  <div class="flex justify-between items-center">
                     <span class="px-3 py-1 bg-gw-bg text-gw-text-muted rounded-lg text-[8px] font-black uppercase tracking-widest italic">{{ mistake.type }} — {{ mistake.tag }}</span>
                     <button (click)="practiceMistake()" class="text-gw-primary hover:scale-110 transition-transform">
                        <i-lucide [img]="NextIcon" size="20"></i-lucide>
                     </button>
                  </div>
                  <div class="grid md:grid-cols-2 gap-4">
                     <div class="space-y-1">
                        <p class="text-[8px] font-black text-gw-error/60 uppercase italic">You Said</p>
                        <p class="text-sm font-bold italic line-through decoration-gw-error/20 text-gw-text-muted">"{{ mistake.said }}"</p>
                     </div>
                     <div class="space-y-1">
                        <p class="text-[8px] font-black text-gw-success uppercase italic">Should Be</p>
                        <p class="text-base font-black italic text-gw-text">"{{ mistake.shouldBe }}"</p>
                     </div>
                  </div>
               </div>
            }
         </div>
      </div>

      <!-- Other Members -->
      <div class="space-y-6">
         <h3 class="text-lg font-black text-gw-text italic uppercase tracking-widest border-l-4 border-gw-primary pl-4">Member Performance</h3>
         <div class="bg-white rounded-[40px] border border-gw-card-border overflow-hidden">
            <table class="w-full text-left border-collapse">
               <thead>
                  <tr class="bg-gw-bg/50">
                     <th class="px-8 py-4 text-[10px] font-black uppercase tracking-widest text-gw-text-muted italic">Member</th>
                     <th class="px-8 py-4 text-[10px] font-black uppercase tracking-widest text-gw-text-muted italic">Fluency</th>
                     <th class="px-8 py-4 text-[10px] font-black uppercase tracking-widest text-gw-text-muted italic">Mistakes</th>
                  </tr>
               </thead>
               <tbody class="divide-y divide-gw-bg">
                  @for (member of detail()?.memberScores; track member.name) {
                    <tr class="hover:bg-gw-bg/20 transition-colors">
                       <td class="px-8 py-6 flex items-center gap-3">
                          <img [src]="'https://api.dicebear.com/7.x/avataaars/svg?seed=' + member.name" class="w-8 h-8 rounded-lg bg-gw-bg">
                          <span class="font-bold italic text-gw-text">{{ member.name }}</span>
                       </td>
                       <td class="px-8 py-6">
                          <div class="flex items-center gap-2">
                             <span class="text-sm font-black italic">{{ member.fluency }}%</span>
                             <div class="w-16 h-1 rounded-full bg-gw-bg flex-shrink-0">
                                <div class="h-full bg-gw-primary rounded-full transition-all duration-1000" [style.width.%]="member.fluency"></div>
                             </div>
                          </div>
                       </td>
                       <td class="px-8 py-6">
                          <span class="text-xs font-black italic text-gw-error">{{ member.mistakes }} errors</span>
                       </td>
                    </tr>
                  }
               </tbody>
            </table>
         </div>
      </div>

      <!-- Final Actions -->
      <div class="grid md:grid-cols-3 gap-4 pt-8">
         <button (click)="practiceMistake()" class="h-16 bg-gw-text text-white font-black uppercase tracking-widest italic rounded-2xl shadow-xl shadow-gw-text/20 hover:scale-[1.02] transition-all flex items-center justify-center gap-3">
            <i-lucide [img]="ZapIcon" size="20" class="text-gw-accent"></i-lucide>
            START CORRECTION ROUND
         </button>
         <button routerLink="/scripts" class="h-16 bg-white border-2 border-gw-card-border text-gw-text font-black uppercase tracking-widest italic rounded-2xl flex items-center justify-center gap-3 hover:bg-gw-bg transition-all">
            <i-lucide [img]="BookIcon" size="20"></i-lucide>
            VIEW SCRIPT
         </button>
         <button (click)="practiceAgain()" class="h-16 bg-white border-2 border-gw-card-border text-gw-text font-black uppercase tracking-widest italic rounded-2xl flex items-center justify-center gap-3 hover:bg-gw-bg transition-all">
            <i-lucide [img]="RetryIcon" size="20"></i-lucide>
            PRACTICE AGAIN
         </button>
      </div>
    </div>
  `,
  styles: [`
    :host { display: block; }
  `]
})
export class SessionDetailComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private userService = inject(UserService);
  private repracticeService = inject(RepracticeService);
  private toast = inject(ToastService);

  readonly BackIcon = ChevronLeft;
  readonly CalendarIcon = Calendar;
  readonly ClockIcon = Clock;
  readonly AwardIcon = Award;
  readonly NextIcon = ArrowRight;
  readonly ZapIcon = Zap;
  readonly BookIcon = BookOpen;
  readonly RetryIcon = RotateCcw;
  readonly InfoIcon = Info;

  detail = signal<SessionDetail | null>(null);

  ngOnInit() {
    this.route.params.subscribe(params => {
      const id = params['sessionId'];
      if (id) {
        this.userService.getSessionDetail(id).subscribe(res => {
          this.detail.set(res);
        });
      }
    });
  }

  practiceMistake() {
    this.repracticeService.generateRepracticeSession(this.detail()?.id || '0').subscribe(res => {
      this.router.navigate(['/repractice', res.id]);
    });
  }

  practiceAgain() {
    this.router.navigate(['/session/create'], { queryParams: { scriptId: this.detail()?.scriptId } });
  }
}

// src/pages/User/SessionDetail.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { 
  ChevronLeft, 
  Timer, 
  Target, 
  Zap, 
  TrendingUp, 
  MessageSquare, 
  CheckCircle2, 
  RotateCcw,
  BookOpen,
  Volume2,
  Users,
  Star,
  Activity,
  Calendar
} from 'lucide-react';
import { doc, getDoc, collection, query, where, getDocs } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { Session, Mistake, Script } from '@/types';
import { format } from 'date-fns';

import { useAuth } from '@/lib/AuthContext';
import { DUMMY_SESSIONS } from '@/data/dummy/session.dummy';
import { DUMMY_SCRIPTS } from '@/data/dummy/script.dummy';
import { DUMMY_MISTAKES } from '@/data/dummy/mistake.dummy';

export default function SessionDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { isDemo } = useAuth();
  const [session, setSession] = useState<Session | null>(null);
  const [mistakes, setMistakes] = useState<Mistake[]>([]);
  const [script, setScript] = useState<Script | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;

    const fetchDetail = async () => {
      try {
        if (isDemo) {
          const sData = DUMMY_SESSIONS.find(s => s.id === id);
          if (sData) {
            setSession(sData);
            if (sData.scriptId) {
              const scrData = DUMMY_SCRIPTS.find(sc => sc.id === sData.scriptId);
              if (scrData) setScript(scrData);
            }
            const mData = DUMMY_MISTAKES.filter(m => m.sessionId === id);
            setMistakes(mData);
          }
          setLoading(false);
          return;
        }

        const sSnap = await getDoc(doc(db, 'sessions', id));
        if (sSnap.exists()) {
          const sData = { id: sSnap.id, ...sSnap.data() } as Session;
          setSession(sData);

          if (sData.scriptId) {
            const scrSnap = await getDoc(doc(db, 'scripts', sData.scriptId));
            if (scrSnap.exists()) {
              setScript({ id: scrSnap.id, ...scrSnap.data() } as Script);
            }
          }

          const mQuery = query(collection(db, 'mistakes'), where('sessionId', '==', id));
          const mSnap = await getDocs(mQuery);
          setMistakes(mSnap.docs.map(d => ({ id: d.id, ...d.data() } as Mistake)));
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchDetail();
  }, [id]);

  if (loading) return (
     <div className="min-h-screen bg-gwf-bg flex items-center justify-center">
        <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-gwf-primary" />
     </div>
  );

  if (!session) return (
    <div className="min-h-screen bg-gwf-bg flex flex-col items-center justify-center p-6 text-center">
       <Activity size={48} className="text-gwf-muted opacity-20 mb-4" />
       <h2 className="text-xl font-black italic">Session Not Found</h2>
       <button onClick={() => navigate(-1)} className="mt-4 text-gwf-primary font-bold">Go Back</button>
    </div>
  );

  const fluencyColor = (session.lastEvaluation?.overallScore || 0) >= 80 ? 'text-gwf-success' : (session.lastEvaluation?.overallScore || 0) >= 60 ? 'text-gwf-warning' : 'text-gwf-error';
  const bgFluency = (session.lastEvaluation?.overallScore || 0) >= 80 ? 'bg-gwf-success/10 border-gwf-success/20' : (session.lastEvaluation?.overallScore || 0) >= 60 ? 'bg-gwf-warning/10 border-gwf-warning/20' : 'bg-gwf-error/10 border-gwf-error/20';

  return (
    <div className="min-h-screen bg-gwf-bg pb-24">
      <header className="p-6 bg-white border-b border-gwf-border sticky top-0 z-10 flex items-center justify-between">
         <div className="flex items-center gap-3">
            <button onClick={() => navigate(-1)} className="p-2 hover:bg-gwf-bg rounded-xl transition-all">
               <ChevronLeft size={20} className="text-gwf-muted" />
            </button>
            <h1 className="text-xl font-black italic tracking-tight">Sync Analysis</h1>
         </div>
         <div className="px-3 py-1 bg-gwf-primary/10 text-gwf-primary text-[9px] font-black uppercase rounded-lg border border-gwf-primary/20">
            {session.sessionMode}
         </div>
      </header>

      <main className="max-w-4xl mx-auto p-6 space-y-10">
        {/* Basic Info */}
        <div className="space-y-2">
           <p className="text-[10px] font-black uppercase tracking-widest text-gwf-muted italic">Performance Summary</p>
           <h2 className="text-2xl font-black italic">{session.sessionName}</h2>
           <div className="flex flex-wrap gap-4 text-[10px] text-gwf-muted font-bold uppercase tracking-wider">
              <span className="flex items-center gap-1.5">
                <Calendar size={12} /> 
                {session.createdDate 
                  ? format(
                      session.createdDate.seconds 
                        ? new Date(session.createdDate.seconds * 1000) 
                        : new Date(session.createdDate), 
                      'MMM d, yyyy'
                    )
                  : 'Recent'}
              </span>
              <span className="flex items-center gap-1.5"><Timer size={12} /> 12 Minutes</span>
              <span className="flex items-center gap-1.5"><Users size={12} /> {session.maxMembers} Members</span>
           </div>
        </div>

        {/* Score Grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
           <div className={`card-base p-6 text-center space-y-2 ${bgFluency}`}>
              <p className={`text-4xl font-black italic tracking-tighter ${fluencyColor}`}>{session.lastEvaluation?.overallScore || 0}%</p>
              <p className="text-[9px] font-black uppercase text-gwf-muted tracking-widest">Fluency Sync</p>
           </div>
           <ScoreCard icon={<Zap size={14} className="text-gwf-accent" />} label="Confidence" value={`${session.lastEvaluation?.confidenceScore || 0}%`} />
           <ScoreCard icon={<TrendingUp size={14} className="text-gwf-primary" />} label="Speed" value={`${session.lastEvaluation?.speakingSpeedWPM || 0} wpm`} />
           <ScoreCard icon={<MessageSquare size={14} className="text-gwf-warning" />} label="Mistakes" value={mistakes.length} />
        </div>

        {/* Mistakes Section */}
        <section className="space-y-4">
           <div className="flex items-center justify-between">
              <h3 className="text-sm font-black italic uppercase text-gwf-muted">My Session Challenges</h3>
              <span className="text-[10px] font-bold text-gwf-error bg-gwf-error/5 px-2 py-0.5 rounded border border-gwf-error/10">{mistakes.length} Red Fixes</span>
           </div>
           
           <div className="grid gap-3">
              {mistakes.map((m) => (
                <div key={m.id} className="glass p-5 rounded-[28px] border border-gwf-border flex flex-col md:flex-row md:items-center justify-between gap-4">
                   <div className="space-y-2">
                       <div className="flex items-center gap-2">
                          <span className={`px-2 py-0.5 rounded text-[8px] font-black uppercase tracking-widest ${m.mistakeType === 'GRAMMAR' ? 'bg-gwf-primary/10 text-gwf-primary' : 'bg-gwf-accent/10 text-gwf-accent'}`}>
                             {m.mistakeType}
                          </span>
                          {m.grammarTag && <span className="text-[8px] font-bold text-gwf-muted italic">{m.grammarTag}</span>}
                       </div>
                       <div className="space-y-0.5">
                          <p className="text-xs text-gwf-error line-through opacity-40 italic">"{m.spokenText}"</p>
                          <p className="text-sm font-bold italic text-gwf-text">"{m.utteranceText}"</p>
                       </div>
                   </div>
                   <button 
                     onClick={() => navigate('/repractice/new')}
                     className="px-5 py-2 bg-gwf-primary/5 text-gwf-primary text-[10px] font-black uppercase rounded-full border border-gwf-primary/10 hover:bg-gwf-primary hover:text-white transition-all whitespace-nowrap"
                   >
                      Refine Sync
                   </button>
                </div>
              ))}
              {mistakes.length === 0 && (
                <div className="card-base py-12 text-center space-y-2 border-dashed">
                   <CheckCircle2 size={32} className="mx-auto text-gwf-success opacity-20" />
                   <p className="text-sm font-bold italic text-gwf-muted">Pure Sync Perfection. No mistakes recorded.</p>
                </div>
              )}
           </div>
        </section>

        {/* Feedback Section */}
        <section className="grid md:grid-cols-2 gap-8">
           <div className="space-y-4">
              <h3 className="text-sm font-black italic uppercase text-gwf-muted">Listener Feedbacks</h3>
              <div className="bg-white rounded-[32px] border border-gwf-border p-6 shadow-sm divide-y divide-gwf-border/50">
                 <FeedbackRow label="Perfect Sync" count={8} icon={<CheckCircle2 size={16} className="text-gwf-success" />} />
                 <FeedbackRow label="Minor Hesitation" count={2} icon={<Target size={16} className="text-gwf-warning" />} />
                 <FeedbackRow label="Unclear Tone" count={1} icon={<Volume2 size={16} className="text-gwf-primary" />} />
                 <FeedbackRow label="Accuracy Miss" count={1} icon={<AlertCircle size={16} className="text-gwf-error" />} />
              </div>
           </div>

           <div className="space-y-4">
              <h3 className="text-sm font-black italic uppercase text-gwf-muted">Partner Scores</h3>
              <div className="bg-white rounded-[32px] border border-gwf-border overflow-hidden shadow-sm">
                 <table className="w-full text-left">
                    <thead className="bg-gwf-bg border-b border-gwf-border">
                       <tr>
                          <th className="px-6 py-3 text-[9px] font-black uppercase tracking-widest text-gwf-muted">Member</th>
                          <th className="px-6 py-3 text-[9px] font-black uppercase tracking-widest text-gwf-muted">Fluency</th>
                          <th className="px-6 py-3 text-[9px] font-black uppercase tracking-widest text-gwf-muted">Mistakes</th>
                       </tr>
                    </thead>
                    <tbody className="divide-y divide-gwf-border">
                       <PartnerRow name="Aarav" score="88%" mistakes={2} />
                       <PartnerRow name="Ishani" score="91%" mistakes={1} />
                       <PartnerRow name="Rahul" score="75%" mistakes={4} />
                    </tbody>
                 </table>
              </div>
           </div>
        </section>

        {/* Actions */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
           <button 
             onClick={() => navigate('/repractice/new')}
             className="w-full h-16 btn-primary rounded-3xl flex items-center justify-center gap-3 italic font-black text-lg shadow-xl shadow-gwf-primary/30"
           >
              Start Correction Round <RotateCcw size={22} />
           </button>
           <button 
             onClick={() => navigate('/')}
             className="w-full h-16 bg-white border-2 border-gwf-border rounded-3xl flex items-center justify-center gap-3 italic font-black text-lg hover:bg-gwf-bg transition-all"
           >
              Back to Dashboard
           </button>
        </div>

      </main>
    </div>
  );
}

function ScoreCard({ icon, label, value }: { icon: React.ReactNode, label: string, value: string | number }) {
  return (
    <div className="card-base p-6 text-center space-y-2">
       <div className="flex justify-center">{icon}</div>
       <p className="text-2xl font-black italic tracking-tighter">{value}</p>
       <p className="text-[9px] font-black uppercase text-gwf-muted tracking-widest">{label}</p>
    </div>
  );
}

function FeedbackRow({ label, count, icon }: { label: string, count: number, icon: React.ReactNode }) {
  return (
    <div className="flex items-center justify-between py-4 first:pt-0 last:pb-0">
       <div className="flex items-center gap-3">
          {icon}
          <span className="text-xs font-bold italic">{label}</span>
       </div>
       <span className="px-2 py-0.5 bg-gwf-bg rounded text-[10px] font-black text-gwf-primary">{count}</span>
    </div>
  );
}

function PartnerRow({ name, score, mistakes }: { name: string, score: string, mistakes: number }) {
  return (
    <tr>
       <td className="px-6 py-4">
          <div className="flex items-center gap-2">
             <div className="w-6 h-6 rounded-lg bg-gwf-bg border border-gwf-border overflow-hidden">
                <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${name}`} className="w-full h-full" alt={name} />
             </div>
             <span className="text-xs font-bold">{name}</span>
          </div>
       </td>
       <td className="px-6 py-4 text-xs font-black italic">{score}</td>
       <td className={`px-6 py-4 text-xs font-black ${mistakes > 2 ? 'text-gwf-error' : 'text-gwf-success'}`}>{mistakes}</td>
    </tr>
  );
}

function AlertCircle({ size, className }: { size: number, className: string }) {
  return <Volume2 size={size} className={className} />;
}
