// src/pages/Assessment/SessionReport.tsx
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'motion/react';
import { 
  CheckCircle2, 
  TrendingUp, 
  Calendar, 
  Clock, 
  Target, 
  Star, 
  Users, 
  ArrowRight,
  RotateCcw,
  Volume2,
  Trophy,
  Activity,
  History,
  LayoutDashboard,
  Download
} from 'lucide-react';
import { useAuth } from '@/lib/AuthContext';
import { db } from '@/lib/firebase';
import { doc, getDoc, collection, query, where, getDocs } from 'firebase/firestore';
import { Session, Assessment, Member } from '@/types';
import { DUMMY_SESSIONS } from '@/data/dummy/session.dummy';

export default function SessionReport() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { user, isDemo } = useAuth();
  const [session, setSession] = useState<Session | null>(null);
  const [assessments, setAssessments] = useState<Assessment[]>([]);
  const [members, setMembers] = useState<Member[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;

    const fetchReport = async () => {
      try {
        if (isDemo) {
          const sData = DUMMY_SESSIONS.find(s => s.id === id);
          if (sData) {
            setSession(sData);
          }
          setLoading(false);
          return;
        }

        const sSnap = await getDoc(doc(db, 'sessions', id));
        if (sSnap.exists()) {
          setSession({ id: sSnap.id, ...sSnap.data() } as Session);

          // Fetch members from subcollection
          const mSnap = await getDocs(collection(db, 'sessions', id, 'members'));
          setMembers(mSnap.docs.map(d => ({ id: d.id, ...d.data() } as Member)));

          // Fetch assessments for the session
          const aQuery = query(collection(db, 'assessments'), where('sessionId', '==', id));
          const aSnap = await getDocs(aQuery);
          setAssessments(aSnap.docs.map(d => ({ id: d.id, ...d.data() } as Assessment)));
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchReport();
  }, [id]);

  if (loading) return (
     <div className="min-h-screen bg-gwf-bg flex items-center justify-center">
        <div className="animate-spin h-10 w-10 border-t-2 border-gwf-primary rounded-full"></div>
     </div>
  );

  if (!session && !loading) {
     return (
        <div className="min-h-screen bg-gwf-bg flex flex-col items-center justify-center p-6 text-center">
           <Activity size={48} className="text-gwf-muted opacity-20 mb-4" />
           <h2 className="text-xl font-black italic">Report Not Found</h2>
           <button onClick={() => navigate(-1)} className="mt-4 text-gwf-primary font-bold">Go Back</button>
        </div>
     );
  }

  if (!session) return null;

  // Calculate stats for current user
  const myAssessments = assessments.filter(a => a.candidateMemberId === user?.id);
  const avgFluency = myAssessments.length > 0 
    ? Math.round(myAssessments.reduce((acc, a) => acc + (a.ratings?.fluency || 0), 0) / myAssessments.length) * 20
    : 75; // Default for demo if no assessments yet

  // Best performer logic (simulated for demo if needed)
  const memberScores = members.length > 0 ? members.map(m => {
    const memberAssessments = assessments.filter(a => a.candidateMemberId === m.userId);
    const score = memberAssessments.length > 0 
      ? Math.round(memberAssessments.reduce((acc, a) => acc + (a.ratings?.fluency || 0), 0) / memberAssessments.length) * 20
      : Math.round(70 + Math.random() * 20);
    return { ...m, avgScore: score };
  }) : [
     { id: '1', name: user?.fullName || 'You', userId: user?.id, avgScore: avgFluency, avatar: user?.avatar },
     { id: '2', name: 'Aarav', userId: 'u2', avgScore: 88, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aarav' },
     { id: '3', name: 'Ishani', userId: 'u3', avgScore: 92, avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ishani' }
  ];

  const bestPerformer = [...memberScores].sort((a, b) => b.avgScore - a.avgScore)[0];

  return (
    <div className="min-h-screen bg-gwf-bg selection:bg-gwf-primary/20 pb-24">
      <main className="max-w-3xl mx-auto p-6 md:p-12 space-y-12">
        
        {/* Celebration Header */}
        <section className="text-center space-y-6 pt-8">
           <motion.div 
             initial={{ scale: 0.8, opacity: 0 }}
             animate={{ scale: 1, opacity: 1 }}
             className="w-24 h-24 bg-gwf-success/20 rounded-[40px] flex items-center justify-center text-gwf-success mx-auto shadow-[0_0_50px_rgba(34,197,94,0.15)]"
           >
              <Trophy size={48} />
           </motion.div>
           
           <div className="space-y-2">
              <h1 className="text-4xl font-black italic tracking-tight text-gwf-text">Session Complete! ✓</h1>
              <div className="flex items-center justify-center gap-2 text-gwf-muted font-bold text-[10px] uppercase tracking-widest italic">
                 <span>{session.sessionName}</span>
                 <span className="w-1 h-1 bg-gwf-border rounded-full" />
                 <span>12 Minutes Sync</span>
              </div>
           </div>

           <div className="flex justify-center print:hidden">
              <button 
                onClick={() => window.print()}
                className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-gwf-primary bg-gwf-primary/5 px-4 py-2 rounded-xl border border-gwf-primary/10 hover:bg-gwf-primary/10 transition-all"
              >
                <Download size={14} /> Export PDF Report
              </button>
           </div>
        </section>

        {/* Global Stats Grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
           <ReportStat label="Avg Fluency" value={`${avgFluency}%`} color="text-gwf-primary" icon={<TrendingUp size={14} />} />
           <ReportStat label="Turns Sync'd" value={myAssessments.length || 10} color="text-gwf-text" icon={<History size={14} />} />
           <ReportStat label="Mistakes" value={5} color="text-gwf-error" icon={<Activity size={14} />} />
           <ReportStat label="Group Growth" value="+12%" color="text-gwf-accent" icon={<Star size={14} />} />
        </div>

        {/* Members Leaderboard */}
        <section className="space-y-4">
           <div className="flex items-center justify-between px-2">
              <h2 className="text-sm font-black italic uppercase text-gwf-muted px-1">Sync Leaderboard</h2>
              <div className="flex items-center gap-2 text-[10px] font-bold text-gwf-muted italic">
                 <Users size={12} /> {memberScores.length} Members Participated
              </div>
           </div>

           <div className="bg-white rounded-[40px] border border-gwf-border overflow-hidden shadow-sm">
              <table className="w-full text-left border-collapse">
                 <thead className="bg-gwf-bg/50 border-b border-gwf-border">
                    <tr>
                       <th className="px-6 py-4 text-[9px] font-black uppercase tracking-widest text-gwf-muted">Member</th>
                       <th className="px-6 py-4 text-[9px] font-black uppercase tracking-widest text-gwf-muted">Fluency</th>
                       <th className="px-6 py-4 text-[9px) font-black uppercase tracking-widest text-gwf-muted text-right">Rating</th>
                    </tr>
                 </thead>
                 <tbody className="divide-y divide-gwf-border">
                    {memberScores.map((m) => (
                      <tr key={m.userId} className={`${m.userId === bestPerformer?.userId ? 'bg-gwf-secondary/5' : ''} transition-colors`}>
                         <td className="px-6 py-4">
                            <div className="flex items-center gap-3">
                               <div className="w-8 h-8 rounded-xl bg-white border border-gwf-border p-0.5 overflow-hidden shadow-sm">
                                  <img src={m.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${m.name}`} className="w-full h-full object-cover rounded-lg" alt={m.name} />
                               </div>
                               <div className="flex flex-col">
                                  <span className="text-xs font-black italic">{m.name} {m.userId === user?.id && <span className="text-[8px] font-medium text-gwf-primary opacity-60">(You)</span>}</span>
                                  {m.userId === bestPerformer?.userId && <span className="text-[8px] font-black uppercase text-gwf-secondary flex items-center gap-1"><Trophy size={8} /> MVP</span>}
                               </div>
                            </div>
                         </td>
                         <td className="px-6 py-4">
                            <span className={`text-sm font-black italic ${m.avgScore >= 80 ? 'text-gwf-success' : m.avgScore >= 60 ? 'text-gwf-warning' : 'text-gwf-error'}`}>
                               {m.avgScore}%
                            </span>
                         </td>
                         <td className="px-6 py-4 text-right">
                            <div className="flex items-center justify-end gap-0.5">
                               {Array.from({ length: 5 }).map((_, i) => (
                                 <Star key={i} size={10} className={i < Math.floor(m.avgScore / 20) ? 'fill-gwf-warning text-gwf-warning' : 'text-gwf-border'} />
                               ))}
                            </div>
                         </td>
                      </tr>
                    ))}
                 </tbody>
              </table>
           </div>
        </section>

        {/* Improvement Insight */}
        <section className="bg-gwf-primary/5 rounded-[40px] border border-gwf-primary/10 p-8 flex flex-col md:flex-row items-center gap-8 shadow-inner">
           <div className="w-16 h-16 bg-gwf-primary rounded-3xl flex items-center justify-center text-white shadow-xl shadow-gwf-primary/20">
              <TrendingUp size={32} />
           </div>
           <div className="flex-1 space-y-1 text-center md:text-left">
              <h3 className="text-lg font-black italic">Rhythm Synchronized!</h3>
              <p className="text-sm font-medium italic text-gwf-muted">Your group improved collective fluency by <span className="text-gwf-primary font-bold">12%</span> compared to previous sessions on this script.</p>
           </div>
        </section>

        {/* Action Buttons */}
        <div className="flex flex-col gap-4">
           <button 
             onClick={() => navigate('/repractice/new')}
             className="w-full h-16 btn-primary rounded-3xl glow-primary flex items-center justify-center gap-3 italic font-black text-xl shadow-2xl"
           >
              Refine Your Mistakes <RotateCcw size={22} />
           </button>
           
           <div className="grid grid-cols-2 gap-4">
              <button 
                onClick={() => navigate(`/user/sessions/${id}`)}
                className="h-14 bg-white border-2 border-gwf-border rounded-[28px] flex items-center justify-center gap-2 font-black italic text-sm hover:border-gwf-primary/30 transition-all shadow-sm"
              >
                 Detailed Report <ArrowRight size={18} />
              </button>
              <button 
                onClick={() => navigate('/')}
                className="h-14 bg-white border-2 border-gwf-border rounded-[28px] flex items-center justify-center gap-2 font-black italic text-sm hover:border-gwf-primary/30 transition-all shadow-sm"
              >
                 Back to Dashboard <LayoutDashboard size={18} />
              </button>
           </div>
        </div>

      </main>
    </div>
  );
}

function ReportStat({ label, value, color, icon }: { label: string, value: string | number, color: string, icon: React.ReactNode }) {
  return (
    <div className="card-base flex flex-col gap-2 py-6 text-center hover:scale-105 transition-transform cursor-default">
       <div className="flex justify-center text-gwf-muted opacity-40">{icon}</div>
       <p className={`text-2xl font-black italic tracking-tighter ${color}`}>{value}</p>
       <p className="text-[9px] font-black uppercase text-gwf-muted tracking-widest">{label}</p>
    </div>
  );
}

// src/app/modules/session/report/session-report.component.ts
import { Component, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { LucideAngularModule, Trophy, Star, Clock, AlertCircle, ChevronRight, Share2, ClipboardList, Target, Zap, RotateCcw } from 'lucide-angular';
import { HeaderComponent } from '@shared/components/header/header.component';
import { BottomNavComponent } from '@shared/components/bottom-nav/bottom-nav.component';
import { DemoBannerComponent } from '@shared/components/demo-banner/demo-banner.component';
import { LiveSessionService } from '@core/services/live-session.service';
import { RepracticeService } from '@core/services/repractice.service';
import { LoaderService } from '@core/services/loader.service';
import { ToastService } from '@core/services/toast.service';

@Component({
  selector: 'app-session-report',
  standalone: true,
  imports: [CommonModule, LucideAngularModule, HeaderComponent, BottomNavComponent, DemoBannerComponent, RouterLink],
  template: `
    <div class="min-h-screen bg-ls-bg pb-24">
      <app-demo-banner></app-demo-banner>
      <app-header title="Session Summary" [showBack]="true"></app-header>

      <!-- Loader Overlay -->
      <div *ngIf="loader.isLoading()" class="fixed inset-0 bg-ls-bg/80 backdrop-blur-sm z-50 flex flex-col items-center justify-center gap-4">
         <div class="w-12 h-12 border-4 border-ls-primary border-t-transparent rounded-full animate-spin"></div>
         <p class="text-[10px] font-black uppercase tracking-[0.3em] text-ls-primary">Processing...</p>
      </div>

      <main *ngIf="summary()" class="p-6 space-y-8 animate-in fade-in duration-500">
        <!-- Hero Score Area -->
        <div class="card bg-ls-focus-bg text-ls-focus-text p-10 text-center relative overflow-hidden border-none rounded-3xl shadow-2xl">
          <div class="relative z-10 space-y-2">
            <p class="text-[10px] font-black uppercase tracking-[0.4em] opacity-50">Mastery</p>
            <div class="flex items-center justify-center gap-4">
              <span class="text-7xl font-black italic tracking-tighter text-white">{{ summary().fluencyScore ?? summary().score ?? 0 }}%</span>
              <div class="flex items-center gap-1 text-ls-accent">
                <i-lucide [img]="StarIcon" size="24" fill="currentColor"></i-lucide>
              </div>
            </div>
            <p class="text-xs font-bold uppercase tracking-widest opacity-70 mt-4">{{ summary().scriptTitle || 'English Fluency Session' }}</p>
          </div>
          <i-lucide [img]="TrophyIcon" size="180" class="absolute -right-12 -bottom-12 opacity-5"></i-lucide>
        </div>

        <!-- Quick Stats Grid -->
        <div class="grid grid-cols-2 gap-4">
          <div class="card p-6 border-ls-card-border flex flex-col items-center gap-2 bg-white shadow-sm">
            <i-lucide [img]="TargetIcon" size="20" class="text-ls-primary"></i-lucide>
            <p class="text-[8px] font-black uppercase tracking-widest text-ls-text-muted">Total Turns</p>
            <p class="text-xl font-black italic text-ls-text">{{ summary().totalTurns || 0 }}</p>
          </div>
          <div class="card p-6 border-ls-card-border flex flex-col items-center gap-2 bg-white shadow-sm">
            <i-lucide [img]="AlertIcon" size="20" class="text-ls-error"></i-lucide>
            <p class="text-[8px] font-black uppercase tracking-widest text-ls-text-muted">Team Mistakes</p>
            <p class="text-xl font-black italic text-ls-text">{{ summary().totalMistakesAllMembers ?? summary().mistakesCount ?? 0 }}</p>
          </div>
        </div>

        <!-- Individual Performance -->
        <section class="space-y-4">
          <div class="flex items-center justify-between px-1">
            <h3 class="text-xs font-black uppercase tracking-[0.2em] text-ls-text-muted flex items-center gap-2">
              <i-lucide [img]="ClipboardIcon" size="14"></i-lucide>
              Performance Breakdown
            </h3>
          </div>
          <div class="space-y-3">
            <div *ngFor="let m of summary().memberScores || summary().members" 
                 class="card p-5 border flex items-center justify-between shadow-sm transition-all"
                 [ngClass]="{
                   'bg-ls-primary/5 border-ls-primary/20': m.userId === bestPerformerId(),
                   'bg-white border-ls-card-border': m.userId !== bestPerformerId()
                 }">
              <div class="flex items-center gap-4">
                <div class="w-10 h-10 rounded-xl bg-ls-bg flex items-center justify-center overflow-hidden border border-ls-card-border relative">
                   <img [src]="'https://api.dicebear.com/7.x/avataaars/svg?seed=' + (m.fullName || m.name)" class="w-full h-full object-cover">
                   <div *ngIf="m.userId === bestPerformerId()" class="absolute -top-1 -right-1 bg-ls-accent text-white rounded-full p-0.5">
                      <i-lucide [img]="StarIcon" size="8" fill="currentColor"></i-lucide>
                   </div>
                </div>
                <div>
                  <h4 class="text-xs font-bold uppercase italic text-ls-text flex items-center gap-2">
                    {{ m.fullName || m.name }}
                    <span *ngIf="m.userId === bestPerformerId()" class="text-[8px] font-black uppercase tracking-widest text-ls-primary">(MVP)</span>
                  </h4>
                  <p class="text-[8px] font-black uppercase tracking-widest text-ls-text-muted">
                    {{ m.mistakeCount ?? m.mistakes ?? 0 }} Mistakes • {{ m.confidenceScore || 0 }}% Confidence
                  </p>
                </div>
              </div>
              <div class="text-right">
                <p class="text-lg font-black italic text-ls-primary">{{ m.fluencyScore ?? m.score }}%</p>
                <div class="w-16 h-1 bg-ls-bg rounded-full overflow-hidden mt-1">
                  <div class="h-full bg-ls-primary" [style.width.%]="m.fluencyScore ?? m.score"></div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <!-- Focus Area -->
        <div class="card p-6 bg-ls-accent/5 border border-ls-accent/20 flex items-center gap-6 rounded-2xl" *ngIf="summary().grammarFocusTag || summary().topGrammarFocus">
           <div class="w-12 h-12 bg-ls-accent/10 text-ls-accent rounded-2xl flex items-center justify-center shrink-0">
              <i-lucide [img]="ZapIcon" size="24"></i-lucide>
           </div>
           <div>
              <p class="text-[8px] font-black uppercase tracking-widest text-ls-accent">Group Focus</p>
              <h4 class="text-sm font-bold uppercase italic text-ls-text">Improve "{{ summary().grammarFocusTag || summary().topGrammarFocus }}"</h4>
           </div>
        </div>

        <!-- Main Actions -->
        <div class="flex flex-col gap-4">
          <button (click)="startCorrectionRound()" 
                  class="h-16 w-full bg-ls-accent text-white rounded-2xl flex items-center justify-center gap-3 font-black uppercase italic tracking-wider shadow-lg active:scale-95 transition-all">
            <i-lucide [img]="RotateCcwIcon" size="18"></i-lucide>
            Start Correction Round
          </button>
          <div class="grid grid-cols-2 gap-4">
            <button class="h-16 bg-ls-primary text-white rounded-2xl flex items-center justify-center gap-3 font-black uppercase italic tracking-wider shadow shadow-ls-primary/50 active:scale-95 transition-all">
              <i-lucide [img]="ShareIcon" size="18"></i-lucide>
              Share PDF
            </button>
            <a routerLink="/user/dashboard" class="h-16 bg-white border border-ls-card-border text-ls-text rounded-2xl flex items-center justify-center gap-3 font-black uppercase italic tracking-wider active:scale-95 transition-all shadow-sm">
              Dashboard
            </a>
          </div>
        </div>
      </main>

      <app-bottom-nav></app-bottom-nav>
    </div>
  `,
  styles: [`
    .card { border-radius: 1.5rem; }
  `]
})
export class SessionReportComponent implements OnInit {
  readonly TrophyIcon = Trophy;
  readonly StarIcon = Star;
  readonly ClockIcon = Clock;
  readonly AlertIcon = AlertCircle;
  readonly NextIcon = ChevronRight;
  readonly ShareIcon = Share2;
  readonly ClipboardIcon = ClipboardList;
  readonly TargetIcon = Target;
  readonly ZapIcon = Zap;
  readonly RotateCcwIcon = RotateCcw;

  summary = signal<any>(null);
  bestPerformerId = computed(() => {
    const s = this.summary();
    if (!s) return null;
    const members = s.memberScores || s.members || [];
    if (members.length === 0) return null;
    return members.reduce((prev: any, current: any) => 
      ((current.fluencyScore ?? current.score) > (prev.fluencyScore ?? prev.score)) ? current : prev
    ).userId;
  });

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private liveSessionService: LiveSessionService,
    private repracticeService: RepracticeService,
    public loader: LoaderService,
    private toast: ToastService
  ) {}

  ngOnInit() {
    // 1. Check navigation state
    const stateSummary = window.history.state?.summary;
    if (stateSummary) {
      this.summary.set(stateSummary);
    } else {
      // 2. Fetch from API if direct navigation
      this.route.params.subscribe(params => {
        const id = params['id'];
        if (id) {
          this.fetchSummary(id);
        }
      });
    }
  }

  fetchSummary(sessionId: string) {
    this.loader.show();
    this.liveSessionService.getSessionDetail(sessionId).subscribe({
      next: (res) => {
        this.summary.set(res);
        this.loader.hide();
      },
      error: () => {
        this.loader.hide();
        this.toast.error('Could not load session report');
        this.router.navigate(['/user/dashboard']);
      }
    });
  }

  startCorrectionRound() {
    const sessionId = this.summary()?.id;
    if (!sessionId) return;

    this.loader.show();
    this.repracticeService.generate(sessionId).subscribe({
      next: (res) => {
        this.loader.hide();
        const rpId = res.repracticeSessionId || res.id;
        if (rpId) {
          this.router.navigate(['/repractice', rpId]);
        } else {
          this.toast.error('Could not start correction round');
        }
      },
      error: () => {
        this.loader.hide();
        this.toast.error('Error generating improvement plan');
      }
    });
  }
}
